### ISSUE TITLE
SP/Jundiai/_pk0025.01 script

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#100]
No Readme.md https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Jundiai/_pk0025.01
Comenta sobre um script

Procedimento usando PostGIS com script desenvolvido pelo A4A.
Cada ponto terá os dados:
Nome do logradouro
Número predial

Onde está esse script?

**Comment by crebollobr** [comment]
@luisfelipebr 
No README
Os endereços poderão ser atribuídos via uma planilha relacionando o gid aos endereços. O pedido solicitando a planilha já foi enviado.


Poderia verificar se recebemos essa planilha de endereços?

**Comment by luisfelipebr** [comment]
@crebollobr nao recebemos planilha de enderecos. Os dados foram analisados pelo Igor ha muito tempo atras. Se voce nao conseguir atribuir o endereco apenas com as informacoes presentes no README, pode fazer upload apenas da geometria dos lotes.

**Comment by crebollobr** [comment]
feito
