### ISSUE TITLE
Cabreuva Gerar eixos de vias com nomes do OpenStreetMap

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#103]
Alguma solução make_conf.yaml para Cabreuva? Gerar eixos de vias com nomes do OpenStreetMap

https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Cabreuva/_pk0040.01

**Comment by crebollobr** [comment]
Levando em conta a discussão #81

**Comment by crebollobr** [comment]
Inclui essa na #80

**Comment by 0e1** [comment]
Isso já existe. 

Mas, atualmente, os dados são obtidos para o país inteiro.

Então, meu entendimento é que essas tarefas antigas de obter dados do OpenStreetMap no nível municipal perderam o sentido.

No caso do Brasil, temos os pacotes:

https://github.com/digital-guard/preserv-BR/tree/main/data/_pk0004.01
https://github.com/digital-guard/preserv-BR/tree/main/data/_pk0004.03

Se quiser ver a consulta que é feita para obter as vias, a partir dos dados brutos:
https://github.com/digital-guard/preserv/blob/main/src/maketemplates/make_ref027a.mustache.mk#L198

E aqui a consulta para obter pontos de endereço:
https://github.com/digital-guard/preserv/blob/main/src/maketemplates/make_ref027a.mustache.mk#L153

**Comment by crebollobr** [comment]
@luisfelipebr Poderia levantar se a prefeitura conseguiria melhores dados.
Com informações geoespaciais?

**Comment by luisfelipebr** [comment]
@ppKrauss temos apenas um csv com o endereço. Faz sentido subir para a plataforma?

**Comment by crebollobr** [comment]
Coloquei um comentário no readme, esperar receber melhores dados da prefeitura
