### ISSUE TITLE
Bug de publicação, revisar Sorocaba e outros que passaram desapercebitos

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#105]
Ver metodologia em https://github.com/digital-guard/preserv/issues/110

Alternativamente, como já publicaram muita coisa, pode testar revisar o que deixou passar direto em http://addressforall.org/teste2/

**Comment by 0e1** [comment]
Provavelmente, ocasionado pelas aspas simples em https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Sorocaba/_pk0031.01/make_conf.yaml#L24.

**Comment by 0e1** [comment]
Revisei, corrigi e republiquei os problemas que encontrei, conforme os commits referenciados acima.
