### ISSUE TITLE
RJ/RioJaneiro/_pk0078.02 Publicação e revisão de make_conf

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv-BR#106]
@crebollobr  e @luisfelipebr Avaliem melhor como se dá o relacionamento de _Lotes_ com _números de porta_ e _logradouros_ em [RioJaneiro/_pk0078.02](https://github.com/digital-guard/preserv-BR/tree/main/data/RJ/RioJaneiro/_pk0078.02).

Meu entendimento é de que _Lotes_ possui apenas identificadores que referenciam  _numeração de porta_ e o _logradouros_. No make_conf está descrito como se _Lotes_ tivesse `via_name` e `house_number`:

```
  parcel:
        subtype: full
        method: geojson2sql
        file: 3
        orig_filename: Lotes_(2013)
        sql_view: |-
              SELECT row_number() OVER () as gid, properties->'cod_trecho' AS via_name, \
              properties->'cod_np' AS house_number,  jgeom AS geom \
              FROM $(tabname)
```

 `cod_np` e `cod_trecho` não parecem ser `house_number` e `via_name`, parecem identificadores que referenciam _numero de porta_ e _logradouros_. Esses relacionamentos são um pra um, um pra muitos?

Pelo que notei, `parcel` parece ser um caso onde seria necessário realizar dois join para obter a geometria do lote com `house_number` e `via_name`. O software não tem essa capacidade atualmente.

Ter em mente que o software é capaz de fazer um join entre layer e seu complemento. Nesse situação, seria possível fazer join entre `parcel` e `cadparcel`, onde `cadparcel` poderia ter informações sobre número de porta ou sobre nome de logradouros.

**Comment by 0e1** [comment]
No commit https://github.com/digital-guard/preserv-BR/commit/9abead1b34413a15a5208ac1ddf4cdf3c3ce9264 fiz as alterações necessárias para obter `via_name` a partir do conteúdo de `via` e incluir em `geoaddress`.

**Comment by 0e1** [comment]
No commit https://github.com/digital-guard/preservCutGeo-BR2021/commit/3c9e3ba35aa17e76c0afb8487daca9ab8bb0f478 publiquei `geoaddress`, `nsvia` e `via` de [RioJaneiro/_pk0078.02](https://github.com/digital-guard/preserv-BR/tree/main/data/RJ/RioJaneiro/_pk0078.02)

**Comment by 0e1** [comment]
Publiquei `block` em https://github.com/digital-guard/preservCutGeo-BR2021/commit/bd1cc5ed55938903bb7461c51d1feabbebbbc34b.

Layer com alto índice de geometrias duplicadas.Ver https://github.com/digital-guard/preserv-BR/issues/102.

**Comment by crebollobr** [comment]
acredito que não tenha mais problemas para resolver
