### ISSUE TITLE
Publicação preservCutGeo-BR2021/tree/Osasco-20220520-01/data/SP/Osasco

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#107]
Publicação em branch

https://github.com/digital-guard/preservCutGeo-BR2021/tree/Osasco-20220520-01/data/SP/Osasco

**Comment by 0e1** [comment]
Faz parte do processo de publicação enviar as informações para `dl03t_main`, conforme https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo#publica%C3%A7%C3%A3o

Assim que fizer isso dou sequencia ao processo de aprovação.

**Comment by 0e1** [comment]
Antes de fazer o envio para dl03t_main, verificar os dados originais ingestados no layer `parcel`. Os dados publicados parecem ser de _loteamentos_ e não de _lotes_:

![Captura de tela de 2022-05-20 22-46-21](https://user-images.githubusercontent.com/41844788/169629763-53729de0-1429-460a-a819-bc7c99518306.png)

**Comment by crebollobr** [comment]
O Readme.md está com informação incorreta.
Como é informação repetida de bairros, vou apagar essa camada

**Comment by crebollobr** [comment]
Corrigi na branch e no README.md

**Comment by 0e1** [comment]
Mas a evidencia de teste mostra os _lotes_ com numeração.

O arquivo _Loteamentos_sirgasUTM.gpkg_ é diferente de _Lotecadastral_numpredial_jun2018_sirgasUTM.gpkg_.

Era _Loteamentos_sirgasUTM.gpkg_ o arquivo referenciado em `parcel`.

Os _lotes_ não estão no arquivo _Lotecadastral_numpredial_jun2018_sirgasUTM.gpkg_?

**Comment by crebollobr** [comment]
Vou criar outra branch para publicar correções

**Comment by 0e1** [comment]
Aprovado, feito o merge e publicado, conforme https://github.com/digital-guard/preserv-BR/issues/108#issuecomment-1133761074.

Ver exemplo: http://addressforall.org/teste2/br-sp-osasco_pk0028.01_block.html.
