### ISSUE TITLE
Publicação de correções em SP/Osasco/_pk0028.01

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#108]
https://github.com/digital-guard/preservCutGeo-BR2021/tree/Osasco-20220521-02/data/SP/Osasco/_pk0028.01

**Comment by crebollobr** [comment]
Feito 
make to_donated_packcomponent pg_db=ingestXX pg_datalake=dl03t_main

**Comment by 0e1** [comment]
Aprovado, feito o merge e publicado.

Ver exemplo: http://addressforall.org/teste2/br-sp-osasco_pk0028.01_block.html.
