### ISSUE TITLE
data/SP/Sorocaba/_pk0031.01

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv-BR#111]
Verificar o `srid` do _layer_ `via` de [Sorocaba](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Sorocaba/_pk0031.01).

Pelos dados publicados no [preservCutGeo](https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/SP/Sorocaba/_pk0031.01/via) e que podem ser visualizados em [br-sp-sorocaba_pk0031.01_via](http://addressforall.org/teste2/br-sp-sorocaba_pk0031.01_via.html), o `srid` é diferente de 31983.

![via](https://user-images.githubusercontent.com/41844788/171725009-20aae554-935d-4aab-b612-4cd77675e41e.png)

**Comment by crebollobr** [comment]
Configurei com srid 5533
Publiquei na branch Sorocaba-20220604-01
https://github.com/digital-guard/preservCutGeo-BR2021/tree/Sorocaba-20220604-01/data/SP/Sorocaba/_pk0031.01

**Comment by 0e1** [comment]
Fiz o merge em https://github.com/digital-guard/preservCutGeo-BR2021/commit/7719ba739aa115cfb65a21f570054da2ff4d2e03 para que @ppKrauss possa fazer limpeza.

No entanto, preciso que você envie os dados para a dl03t_main, conforme o procedimento descrito em https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo#copiar-informa%C3%A7%C3%B5es-para-dl03t_main. Sem isso, não é possível atualizar as páginas na teste2.

**Comment by crebollobr** [comment]
feito o procedimento

**Comment by 0e1** [comment]
Disponível na teste2: http://addressforall.org/teste2/br-sp-sorocaba_pk0031.01_parcel.html
