### ISSUE TITLE
Formato 

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#112]
Link
https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Sorocaba/_pk0031.01

Arquivo make_conf.yaml, layer via com a configuração 

codec: SHP~Latin1;srid=5533

A opção srid é configurada mas ignora o Latin1 na geração do makefile

**Comment by ppKrauss** [comment]
Experimentou ISO-8859-1 ao invés de Latin1?  Em geral o melhor mesmo é evitar sinônimos, usar os nomes canônicos: UTF-8, ISO-8859-1, etc.

@0e1  por favor documentar com precisão a sintaxe `codec`.

**Comment by 0e1** [comment]
Usando a nomenclatura das colunas da tabela [codec_type.csv](https://github.com/digital-guard/preserv/blob/main/data/codec_type.csv), quando o valor da chave `codec` possuir _variant_ e algum valor de `descr_encode` for sobreescrito, o software vai ignorar a `variant` e usar `descr_encode` da _extension_ default (a que possui _variant_ nula na tabela).

Ou seja, não dá pra sobrescrever `descr_encode` de uma linha na tabela dada por `extension~variant`. Portanto, `codec: SHP~Latin1;srid=5533` é equivalente a `codec: SHP;srid=5533` que usa `charset=UTF-8` como _default_.

Se tiver que sobrescrever valores de `descr_encode` usar apenas `extension`.

Assim, a forma correta de expressar:

`codec: SHP~Latin1;srid=5533`

é
`codec: SHP;srid=5533;charset=ISO-8859-1`.

Esse é um comportamento esperado do software, que foi definido, principalmente, em https://github.com/digital-guard/preserv/issues/31#issuecomment-996061179.

**Comment by 0e1** [comment]
> @0e1 por favor documentar com precisão no /docs do Preserv a sintaxe `codec`.

Enquanto isso não acontece, esse comentário resume bem as regras relacionadas a chave codec: https://github.com/digital-guard/preserv/issues/31#issuecomment-996061179

Adicionalmente, sugiro sempre olhar para os valores já existentes nos make_conf na chave codec, para servirem de exemplo para novas situações. : `ag codec preser-BR` retornar os valores.
