### ISSUE TITLE
README.md, nome de arquivo e formato

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#114]
Nos arquivos README.md precisa do nome e formato do arquivo dentro do zip. 
Se é shapefile ou outro formato, principalmente se o zip tiver vários arquivos.

**Comment by crebollobr** [comment]
Precisa adicionar uma imagem ao README.md

**Comment by crebollobr** [comment]
Porque está usando o formato {{#layers}}? 

https://github.com/digital-guard/preserv-BR/tree/main/data/AM/Manaus/_pk0071.01

**Comment by crebollobr** [comment]
Qual a licença dos dados de Fortaleza?

https://github.com/digital-guard/preserv-BR/tree/main/data/CE/Fortaleza/_pk0097.01

**Comment by crebollobr** [comment]
Qual a licença de Vitória?
https://github.com/digital-guard/preserv-BR/tree/main/data/ES/Vitoria/_pk0006.01

**Comment by luisfelipebr** [comment]
> Precisa adicionar uma imagem ao README.md

Qual imagem?

**Comment by luisfelipebr** [comment]
> Porque está usando o formato {{#layers}}?
> 
> https://github.com/digital-guard/preserv-BR/tree/main/data/AM/Manaus/_pk0071.01

Estou utilizando o modelo padrão do README

**Comment by luisfelipebr** [comment]
> Qual a licença de Vitória?
> https://github.com/digital-guard/preserv-BR/tree/main/data/ES/Vitoria/_pk0006.01

CC0. Está na planilha donatedPack

**Comment by crebollobr** [comment]
> > Precisa adicionar uma imagem ao README.md
> 
> Qual imagem?

Imagem do qgis 
Referencia nos README.md antigos
https://github.com/digital-guard/preserv-BR/tree/main/data/SP/RibeiraoPreto/_pk0052.01

**Comment by crebollobr** [comment]
> > Qual a licença dos dados de Fortaleza?
> > https://github.com/digital-guard/preserv-BR/tree/main/data/CE/Fortaleza/_pk0097.01
> 
> CC0. Essa informação está na planilha donatedPack

Coloca no README.md, esse documento é aberto para comunidade e é difícil consultar arquivos de referencia para quem não trabalha com o projeto

**Comment by crebollobr** [comment]
> Coloca no README.md, esse documento é aberto para comunidade e é difícil consultar arquivos de referencia para quem não trabalha com o projeto

Coloca no README.md, esse documento é aberto para comunidade e é difícil consultar arquivos de referencia para quem não trabalha com o projeto

**Comment by crebollobr** [comment]
> > Porque está usando o formato {{#layers}}?
> > https://github.com/digital-guard/preserv-BR/tree/main/data/AM/Manaus/_pk0071.01
> 
> Estou utilizando o modelo padrão do README

Pode ser um erro de grafia ou para usar em templates, não vejo sentido usar esse formato no README.md

**Comment by luisfelipebr** [comment]
@crebollobr vou continuar utilizando esse modelo ate voce disponibilizar um template novo e tutorial para preenchimento. Indique no template novo onde eu devo colocar a informacao de licenca. Nos README que ja estao prontos, eu sugiro que voce edite e adicione essas informacoes faltantes (licenca). Tambem nao entendo a necessidade de adicionar uma figura ilustrativa no QGIS.

Meu entendimento e que o README deveria ser utilizado apenas para auxiliar voce a escrever o yaml. As informacoes mais importantes para a comunidade estao nas tabelas, que vao alimentar o texto amigavel no website. As decisoes tecnicas tambem sao abertas e podem ser consultadas no codigo fonte (yaml)

**Comment by crebollobr** [comment]
O entendimento é que o github é publico e o README.md não deveria ser técnico ao bastante para um leigo não entender. 
Não sei qual template está seguindo mas {{#layers}} não tem sentido no README.md, não faz parte da formatação. A figura é uma prova do que foi escrito no README.md e que possa ser visualizado por todos. 

O Readme.md não é somente para auxiliar a escrever o o make_conf.yaml é uma informação/descrição não técnica dos dados

Se precisar conversamos em reunião na segunda-feira
