### ISSUE TITLE
Ingestão Itanhaém - SP

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv-BR#118]
@crebollobr 

make_conf disponível [aqui](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Itanhaem/_pk0058.01/make_conf.yaml).

Falta construir um sql_view no arquivo via para compor o nome de logradouro.

**Comment by 0e1** [comment]
> Falta construir um sql_view no arquivo via para compor o nome de logradouro.


```
sql_view: |-
     SELECT gid, tr_tipo || ' ' || tr_descric AS via_name, geometry AS geom FROM $(tabname)
```
