### ISSUE TITLE
Ingestão Santa Cruz do Sul - RS

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv-BR#120]
@crebollobr 

make_conf disponível [aqui](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/SantaCruzSul/_pk0064.01/make_conf.yaml).

O único problema que encontrei é o seguinte: em alguns casos, os lotes possuem mais de um número de porta, separados por barra. Não sei o que fazer nesses casos - [ver imagem](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/SantaCruzSul/_pk0064.01/qgis.png).

**Comment by 0e1** [comment]
Nesse caso, não precisa fazer nada. Situações semelhantes a essa não são tratadas no _make_conf_. Elas relevantes e necessitam de tratamento no momento da publicação ou consolidação dos dados.
