### ISSUE TITLE
Coordenadas UTM do Brasil, onde estão os SRIDs oficiais?

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#124]
Ver https://gis.stackexchange.com/q/439303/7505

---

Reparar que não é coisa do "outro mundo", pelo menos para achar o quadrante deve existir algoritmo aberto. Por exemplo algoritmo que transforma um ponto qualquer do Brasil, digamos no Amazonas,  `geo:-4.13,-64.54`, em quadrante UTML (20M) e depois em ponto UTM:
* [geohack da Wikipedia](https://geohack.toolforge.org/geohack.php?pagename=Amazonas&params=4.13_0_0_S_64.54_0_0_W_type:adm1st_scale:100000): fornece `20M 329058 9543337`
* [calculadora do INPE](http://www.dpi.inpe.br/calcula/): com opção de saída com "projeção WGS84", ` 329058.1,  9543337.5; Fuso=20; Meridiano=-63` 
![image](https://user-images.githubusercontent.com/1651447/187076933-2372d92b-f470-4c8c-937b-e4edd5bde1ed.png)
* Meridianos centrais: http://www.jaworski.ca/utmzones.htm

... Mas o PostGIS precisa ainda do SRID do quadrante.

-----

Precisaremos disso para controlar melhor os dados fornecidos por prefeituras, e para mostrar coordenadas no OSMcodes.

## Gambiarra

Uma saída é construir manualmente cada quadrante com seu `proj4text`. Por exemplo com `SELECT srid, substr(srtext,9,26) as EPSG_name,  proj4text FROM spatial_ref_sys WHERE srid IN (31972,31973,31974)`  obtemos:

 srid  | epsg_name |                                 proj4text                                 
-------|-----------|---------------------------------------------------------------------------
31972 | SIRGAS 2000 / UTM zone 18N | `+proj=utm +zone=18 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs`
 31973 | SIRGAS 2000 / UTM zone 19N | `+proj=utm +zone=19 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs`
 31974 | SIRGAS 2000 / UTM zone 20N | `+proj=utm +zone=20 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs`

As *UTM zones* (fusos) possuem "quadrantes `N`" apenas, por estar a "faixa N" sob a linha do Equador... E não aparecem outros  quadrantes na tabela `spatial_ref_sys`. 

Na *PROJ string* (`proj4text`) dos demais quadrantes (não-N tais como 18H, 20etc.) precisamos da correção feita pelo  Meridiano Central de cada quadrante específico da "cobertura Brasil"... A Calculadora INPE pode ajudar, ainda assim precisa testar se de fato  sobrescreve o meridiano central *default*.

**Comment by luisfelipebr** [comment]
@ppKrauss ainda não entendi como resolver essa issue e adiciono outra questão:
Recebemos novos dados em formato Microsoft Access Database (mdb) - tabular com coordenadas, que passam por mais de um SRID UTM e são do Peru.
Podemos marcar uma hora para conversar sobre essa issue e os novos dados?

**Comment by ppKrauss** [comment]
Conclusão dessa *issue*. Ver `utm_grid_cover` e `srid_official` em [/data/conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/conf.yaml).

## Decisão sobre SIRGAS e similares

Conforme [discussão](https://gis.stackexchange.com/a/439316/7505), podemos usar SIRGAS mas recomenda-se o SRID   "WGS 84 / UTM zone {x}{h}" com *x* e *h* equivalentes.

## Metodologia para detectar cobertura e fusos

* Pontos e suas coordenadas UTM. Usar a função [*utmzone_from4326()*](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05pgis-misc.sql#L11) e suas variantes para obter a projeção correta. Usar  *utmgrid_from4326* e suas variantes para fornecer as coordenadas e o rótulo de grade.
* Polígonos de países e sua "cobertura UTMgrid". Usar a função [*utmgrid_from4326_coverlabels*](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05pgis-misc.sql#L98) com p_sample grande suficiente.

-----
## Notas e exemplos

Quando implentar função (UTMgrid_cover) será automático, aqui uma listagem humana, baseada num mapa de confiança.  Sugere-se moldar no texto a sequência espacial para facilitar a verificação.  Cobertura Grid UTM do Brasil, **sem** mar territorial: 
```
               18L, 18M,
               19L, 19M, 19N,
          20K, 20L, 20M, 20N,
     21J, 21K, 21L, 21M, 21N,
22H, 22J, 22K, 22L, 22M, 22N, 
          23K, 23L, 23M,
          24K, 24L, 24M,
          25K, 25L
```

<img width="520" src="https://user-images.githubusercontent.com/1651447/187086297-5f67fe72-5f3b-4d40-9ef4-546db0f877cc.png"/>

Comparando com o resultado de *utmgrid_from4326_coverlabels*, onde foi acrescentado 23J corretamente, depois de 90000 amostragens: 

```
18L,18M,
19L,19M,19N,
20K,20L,20M,20N,
21J,21K,21L,21M,21N,
22H,22J,22K,22L,22M,22N,
23J,23K,23L,23M,
24K,24L,24M,
25L,25M,
26K,26N
```

----

?Projeções oficiais rotuladas como "WGS 84 / UTM zone" <br/>&nbsp; 18➔32618, 19➔32619, 20➔32620, 21➔32621, 22➔32622, 23➔32623, 24➔32624, 25➔32625

?Projeções oficiais rotuladas como "SIRGAS 2000 / UTM zone" <br/>&nbsp; 18➔31972, 19➔31979, 20➔31980, 21➔31981, 22➔31982, 23➔31983, 24➔31984, 25➔31985


Lembretes sobre a função de convesão LatLong para **UTM grid**: *longitude-vertical zones* **vs** *latitude-horizontal bands*, 

* **UTM zones** are numbered ([UTM Zone Number](http://www.jaworski.ca/utmzones.htm)) from `1` to `60` starting from 180° longitude at the International Date Line and proceeding eastward. Each zone is **6° longitude wide**. Therefore Zone `1` lies between 180°W to 174°W longitude lines, Zone `2` is between 174°W and 168°W longitude lines, and Zone `60` lies between 174°E and 180° (International Date Line) longitude lines.   Ver também [Wikipedia/UTM Zone](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#UTM_zone).

* Each zone is divided into *horizontal bands*, **8° of latitude wide**. The 20 bands are labeled with letters ([UTM Zone Designators](http://www.jaworski.ca/utmzones.htm)), beginning with `C` and ending with `X` from south to north. Letters I and O are omitted to prevent confusion. Note that letter `N` designates the first latitude band above the equator (so any letter after `N` refers to northern hemisphere and any `N` refers to a  southern). Ver também [Wikipedia/UTM Latitude bands](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Latitude_bands_2).

[Overlap problem](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Overlapping_grids): somente entre UTM zones (as UTM bands dentro de uma zona não apresentam problema de sobreposição).
