### ISSUE TITLE
Ingestão - Paraná (Estado)

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv-BR#128]
@0e1 não estou conseguindo fazer ingestão de uma doação do estado do Paraná. Como copiar o make me para [essa pasta](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/_pk0059.01)?

**Comment by luisfelipebr** [comment]
@0e1 deu certo! O problema agora foi com o ogr2ogr, encontrei a seguinte mensagem de erro:

> Executando ogr2ogr ...
sudo docker run --rm --network host -v /tmp/sandbox/_pkBR591_001:/tmp osgeo/gdal ogr2ogr -lco GEOMETRY_NAME=geom -overwrite -f "PostgreSQL" PG:" dbname='ingest1' host='localhost' port='5432' user='postgres' " "/tmp/New File Geodatabase (2).gdb" LOTES_PR -nln pk7600005901101_p1_geoaddress 
psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.any_load('gdb2sql','/tmp/sandbox/_pkBR591_001/New File Geodatabase (2).gdb/timestamps','geoaddress_none','pk7600005901101_p1_geoaddress','7600005901101','47dca17c620c1c34ac091dac19afb8851f1d8f9a907094a0f40a0310e774445d.zip',array['gid', 'NrPredial as house_number', 'geom'],1,1)"
ERROR:  could not stat file "/tmp/sandbox/_pkBR591_001/New File Geodatabase (2).gdb/timestamps": No such file or directory
CONTEXT:  SQL function "jsonb_pg_stat_file" statement 1
SQL function "getmeta_to_file" statement 1
SQL function "getmeta_to_file" statement 1
PL/pgSQL function ingest.any_load(text,text,text,text,bigint,text,text[],integer,integer,boolean,text,boolean) line 13 at assignment
make: *** [makefile:77: geoaddress] Error 1

**Comment by 0e1** [comment]
Depois de muito matutar, temos uma solução: https://github.com/digital-guard/preserv/commit/5fe731d53677fc278d26581198514faf0c44c5f6

Pra não esquecermos: _any_load_ necessita de um arquivo para obter um _md5_. No caso de arquivos _gbd_, estava sendo usado um arquivo chamado _timestamps_. O erro reportado indica que esse arquivo nem sempre existe. Assim, a alternativa implementada foi gerar um arquivo de 1 megabyte com conteúdo aleatório, usando o _dd_.

Com isso a ingestão funciona.

Ah, corrigi nome de campos no `sql_select`: https://github.com/digital-guard/preserv-BR/commit/9cb729769d591302811b6c27922b02db5587c2fe

Resultado da ingestão:

```sh

```

**Comment by luisfelipebr** [comment]
Funcionou. Obrigado
