### ISSUE TITLE
rodar e gravar sistematicamente as URLs citadas

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#133]
Ver automação com Claiton em https://github.com/digital-guard/preserv/issues/124

-----
Pendencia:

Todos os itens da coluna "url" da planilha donor 
https://github.com/digital-guard/preserv-BR/blob/main/data/donor.csv
precisam ter confirmação simples de RDAP, ver exemplo de acre.gov.br: 
https://github.com/digital-guard/preserv-BR/blob/main/data/_donorEvidence/br/acre.gov.br/rdap.json
lembrar que é um script de automação: falta incluir no nosso makefile a automação... O PostgreSQL pode gerar essa lista.

**Comment by 0e1** [comment]
Sobre `uri` de um pacote ver: https://github.com/digital-guard/preserv/issues/124#issuecomment-1302605456

**Comment by crebollobr** [comment]
acredito que a issue https://github.com/digital-guard/preserv-BR/issues/133 seja suficiente para essa tarefa
