### ISSUE TITLE
Atualizar os README

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#134]
Fazer os readme resem feitos a partir do make_conf.yaml

**Comment by crebollobr** [comment]
Comentário nos readme novos
Bagé e Jundiai foram feitos o procedimento de correção de charset

**Comment by luisfelipebr** [comment]
Precisamos atualizar o make_conf e README de todos os pacotes listados abaixo

scope | pack_id
-- | --
ES-VilaVelha | 07.01
ES-Vitoria | 06.01
GO-Goiania | 54.01
MG-BeloHorizonte | 08.01
MG-Contagem | 09.01
MG-GovernadorValadares | 39.01
MS-CampoGrande | 34.01
PB-JoaoPessoa | 72.01
PE-Recife | 10.01
PI-Teresina | 45.01
PR-Araucaria | 61.01
PR-Cascavel | 11.01
PR-Maringa | 110.01
PR-Pinhais | 14.01
PR-Toledo | 79.01
RJ-Niteroi | 16.01
RJ-RioJaneiro | 78.02
RN-Natal | 73.01
RO-JiParana | 62.01
RS-CaxiasSul | 69.01
RS-Gravatai | 17.01
RS-Pelotas | 80.01
RS-PortoAlegre | 18.01
RS-SantaMaria | 19.01
SC-Florianopolis | 53.01
SC-Joinville | 35.01
SP-Campinas | 22.01
SP-Guarulhos | 81.01
SP-Itu | 24.01
SP-Limeira | 26.01
SP-Osasco | 28.01
SP-Piracicaba | 41.01
SP-RibeiraoPreto | 52.01
SP-Santos | 29.01
SP-SaoBernardoCampo | 30.01
SP-SaoVicente | 32.01
SP-Sorocaba | 31.01

**Comment by 0e1** [comment]
@IgorEliezer, tarefa pra você assumir. :)
