### ISSUE TITLE
Publicação de make_conf antigos

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv-BR#136]
@0e1 @crebollobr todos os pacotes listados abaixo possuem make_conf, mas não foram publicados. Vou verificar qual o problema com eles (issue aberta, make_conf antigo ou outra) e pedir ajuda de vocês com a publicação.

scope | pack_id | make_conf pronto? | publicado?
-- | -- | -- | --
AM-Manaus | 71.02 | ok | ok 
CE-Fortaleza | 97.01 | ok | ok 
DF-Brasilia | 68.01 | ok | ok 
GO-AparecidaGoiania | 84.01 | ok,  #121 | ok 
PR | 59.01 | ok | ok 
RS-Bage | 82.01 | ok | #140
RS-Canoas | 76.01 | ok | ok
RS-SantaCruzSul | 64.01 | ok | ok
SC-Itajai | 141.01 | ok | ok 
SP-Atibaia | 21.01 | ok | ok
SP-Cabreuva | 40.01 | LIXO | LIXO
SP-Itanhaem | 58.01 | ok |  ok
SP-Jundiai | 25.01 | ok | ok 
SP-SaoJoseCampos | 43.01 | PENDENTE |

**Comment by 0e1** [comment]
Remover SC-Itajai da lista. Publiquei os dados nesse PR: https://github.com/digital-guard/preservCutGeo-BR2021/pull/11.

**Comment by luisfelipebr** [comment]
@0e1 no caso do [Paraná](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/_pk0059.01), o make_conf está pronto, mas o arquivo contém mais de 2,5 milhões de lotes (polígonos). O servidor não deu conta. Você pode ver qual seria a melhor forma de fazer a ingestão e publicação? Dá para dividir por município

**Comment by luisfelipebr** [comment]
@0e1 também vou pedir para você verificar o caso de [Manaus](https://github.com/digital-guard/preserv-BR/tree/main/data/AM/Manaus). O arquivo de lotes do pacote 1 (publicado) não possui endereço completo, enquanto o arquivo de lotes do pacote 2 (ainda não publicado) possui endereço completo. Fiz upload dos dois porque nem todas as geometrias estão nos dois pacotes (algumas do pacote não aparecem no pacote 2 - talvez pq não tenham endereço; ao mesmo tempo, o pacote 2 tem mais observações que o pacote 1). Se você for manter a publicação de apenas 1 delas, precisa ser a do pacote 2.

<img width="1284" alt="Screenshot 2023-01-06 at 16 29 29" src="https://user-images.githubusercontent.com/45462352/211085549-7db26f36-2844-4373-aae7-18e9e289c4df.png">

**Comment by luisfelipebr** [comment]
@crebollobr os seguintes pacotes parecem prontos para ingestão e publicação. Você pode prosseguir com esse processo?
- [Fortaleza](https://github.com/digital-guard/preserv-BR/tree/main/data/CE/Fortaleza/_pk0097.01)
- [Canoas](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/Canoas/_pk0076.01/make_conf.yaml)
- [SantaCruzSul](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/SantaCruzSul/_pk0064.01/make_conf.yaml)
- [Atibaia](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Atibaia/_pk0021.01/make_conf.yaml)
- [Itanhaem](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Itanhaem/_pk0058.01/make_conf.yaml)

Além disso, você pode verificar se [a issue de Aparecida de Goiania](https://github.com/digital-guard/preserv-BR/issues/121) foi resolvida? O [make_conf](https://github.com/digital-guard/preserv-BR/blob/main/data/GO/AparecidaGoiania/_pk0084.01/make_conf.yaml) parece pronto.

**Comment by 0e1** [comment]
> @0e1 no caso do [Paraná](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/_pk0059.01), o make_conf está pronto, mas o arquivo contém mais de 2,5 milhões de lotes (polígonos). O servidor não deu conta. Você pode ver qual seria a melhor forma de fazer a ingestão e publicação? Dá para dividir por município

Existe algum outro campo além de **nrpredial**? Algum outro campo que possa ser utilizado para particionar os dados em conjuntos menores?

**Comment by 0e1** [comment]
> @0e1 também vou pedir para você verificar o caso de [Manaus](https://github.com/digital-guard/preserv-BR/tree/main/data/AM/Manaus). O arquivo de lotes do pacote 1 (publicado) não possui endereço completo, enquanto o arquivo de lotes do pacote 2 (ainda não publicado) possui endereço completo. Fiz upload dos dois porque nem todas as geometrias estão nos dois pacotes (algumas do pacote não aparecem no pacote 2 - talvez pq não tenham endereço; ao mesmo tempo, o pacote 2 tem mais observações que o pacote 1). Se você for manter a publicação de apenas 1 delas, precisa ser a do pacote 2.
> 
> <img alt="Screenshot 2023-01-06 at 16 29 29" width="1284" src="https://user-images.githubusercontent.com/45462352/211085549-7db26f36-2844-4373-aae7-18e9e289c4df.png">

Como foi a história desses dois pacotes de dados? Os dados sobre lotes em [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) foram doados para corrigir a falta de endereços dos lotes em [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml)? Em outras palavras, o doador enviou uma atualização dos dados de lotes?

Me parece que a lista de _files_  em [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml) deve ser  acrescida do sha256 constante em [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml)  e o layer _parcel_  de [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml) passar a referenciar esse novo arquivo, ter seu _pkversion_ incrementado e [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) excluído.

**Comment by luisfelipebr** [comment]
> Como foi a história desses dois pacotes de dados? Os dados sobre lotes em [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) foram doados para corrigir a falta de endereços dos lotes em [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml)? Em outras palavras, o doador enviou uma atualização dos dados de lotes?

Não tenho o histórico, os dados foram doados em 2021 e adicionados no Drive pelo Igor. Os pacotes foram doados com uma diferença de dois meses, acredito que o segundo pacote seja uma atualização do primeiro (embora o primeiro tenha lotes que não estão presentes no segundo pacote).

> Me parece que a lista de files em [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml) deve ser acrescida do sha256 constante em [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) e o layer parcel de [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml) passar a referenciar esse novo arquivo, ter seu pkversion incrementado e [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) excluído.

Fiquei com algumas dúvidas. O pk0071.02 será uma nova pasta e uma nova linha na planilha ou devo editar os arquivos, substituindo "01" por "02"?

**Comment by luisfelipebr** [comment]
> Existe algum outro campo além de nrpredial? Algum outro campo que possa ser utilizado para particionar os dados em conjuntos menores?

@0e1 atualizei o make_conf com o único campo que pode ser utilizado para essa finalidade

**Comment by 0e1** [comment]
> > Como foi a história desses dois pacotes de dados? Os dados sobre lotes em [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) foram doados para corrigir a falta de endereços dos lotes em [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml)? Em outras palavras, o doador enviou uma atualização dos dados de lotes?
> 
> Não tenho o histórico, os dados foram doados em 2021 e adicionados no Drive pelo Igor. Os pacotes foram doados com uma diferença de dois meses, acredito que o segundo pacote seja uma atualização do primeiro (embora o primeiro tenha lotes que não estão presentes no segundo pacote).
> 
> > Me parece que a lista de files em [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml) deve ser acrescida do sha256 constante em [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) e o layer parcel de [71.01](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.01/make_conf.yaml) passar a referenciar esse novo arquivo, ter seu pkversion incrementado e [71.02](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/Manaus/_pk0071.02/make_conf.yaml) excluído.
> 
> Fiquei com algumas dúvidas. O pk0071.02 será uma nova pasta e uma nova linha na planilha ou devo editar os arquivos, substituindo "01" por "02"?

Os commits referenciados log acima desse comentário mostram o que foi feito. Compara o antes/depois em https://github.com/digital-guard/preserv-BR/commit/f97a91a1b7902943cabb537c97789a179324a800 as alterações no make_conf (e remoção de 71.02) e em https://github.com/digital-guard/preserv-BR/commit/c24986bb3c85e07e7321b9a2c570596beab0c582 as alterações na donatePack.csv.

Tratei o 71.02 como atualização dos lotes de 71.01. Com isso a pasta _pk71.02 deixou de existir.

Para esse caso fiz a publicação (https://github.com/digital-guard/preservCutGeo-BR2021/commit/ca3a3b5b73ffce8d998e9460548e8528446767bd) e gerei o readme (https://github.com/digital-guard/preserv-BR/commit/90f44fb381cfee2c27c0ffb04f2ba1ba5568c1a6).

**Comment by 0e1** [comment]
> > > Existe algum outro campo além de nrpredial? Algum outro campo que possa ser utilizado para particionar os dados em conjuntos menores?
> > 
> > 
> > @0e1 atualizei o make_conf com o único campo que pode ser utilizado para essa finalidade
> 
> Usei o campo para viabilizar a ingestão por município. O commit [a2ced17](https://github.com/digital-guard/preserv-BR/commit/a2ced174d2c4d12fdd8abaff96e0a0c33c4e6ee1), referenciado logo acima, mostra como. Nesse momento, a ingestão está acontecendo. Aviso quando terminar.
> 
> Notar que troquei `sql_select` por `sql_view`. Motivo: `partition_by` funciona apenas combinada com `sql_view`.


Ingestão e publicação concluídas.

**Comment by crebollobr** [comment]
acredito que somente São José dos Campos não foi publicado https://github.com/digital-guard/preserv-BR/issues/170
