### ISSUE TITLE
Publicação SP-Jacarei

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv-BR#137]
Alguns ajustes precisam ser feitos no [make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Jacarei/_pk0145.01/make_conf.yaml) antes da ingestão e publicação:

- O arquivo está no formato excel, conferir se subtype está certo (linha 27).
- Adicionar sql_view na linha 30:
     - Remover os pontos na coluna 'Inscrição Imobiliária' e renomear como INSCLOTE
     - Separar tudo que está antes da primeira vírgula na coluna 'Endereço' e renomear para via_name
     - Separar tudo que está depois da primeira vírgula e antes do primeiro hífen e renomear para house_number
- Preencher as linhas 35, 38 e 42 com base no sql_view

A tabela (LOTES_COM_NUMERO_TODOS) possui o seguinte formato:
<img width="645" alt="Screenshot 2023-01-06 at 15 42 18" src="https://user-images.githubusercontent.com/45462352/211077844-77f38c5b-9a67-4f1d-b986-d3e9be3a8ae3.png">

**Comment by 0e1** [comment]
@luisfelipebr fiz os ajustes necessários no _make_conf_ no commit https://github.com/digital-guard/preserv-BR/commit/8bf7004c6ed042125b1a88549363548d6540808d e https://github.com/digital-guard/preserv-BR/commit/8dee463e4714a8452809ed149376ee5fda29f2f8.

Notar que:

- _layer_ tem seu respectivo _layer cadastral_: _parcel_ com _cadparcel_, _geoaddress_ com _address_. Ver https://github.com/digital-guard/preserv/blob/main/docs/pt/ftypes.md (figuras podem estar desatualizadas);
- informar o nome do diretório no campo _orig_filename_, caso a extração resulte em diretório.

Adicionalmente aos itens que elencou, tratei como _nome do bairro_ a string que está após o primeiro hífen que existe após a vírgula. Além disso, removi _espaços_ antes e depois das strings resultantes.

@crebollobr acredito que você já pode prosseguir com o fluxo de trabalho.

**Comment by crebollobr** [comment]
Feito
https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/SP/Jacarei/_pk0145.01
ps. os dados estão um pouco deslocados em relação ao bing

**Comment by crebollobr** [comment]
aguardando aprovação dos dados e alteração dos readmes

**Comment by 0e1** [comment]
Ver https://github.com/digital-guard/preservCutGeo-BR2021/issues/13#issuecomment-1379268346.

**Comment by crebollobr** [comment]
dados publicados
