### ISSUE TITLE
RS/Bage/_pk0082.01: Ingestão Bage RS

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv-BR#140]
Necessário atualizar o sql_view da camada parcel no [make_conf](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/Bage/_pk0082.01/make_conf.yaml).

'numero' = 'house_number' (falta adicionar no sql_view)

'logradouro' = 'via_name' (necessario corrigir a string)

A string do logradouro segue um padrão claro. Eu tenho certeza de que dá para construir um regex que arruma ela, mas não sei como. @0e1 @crebollobr vcs podem ajudar?

<img width="703" alt="Screenshot 2023-02-24 at 17 16 02" src="https://user-images.githubusercontent.com/45462352/221283935-8cf773a8-3ede-4128-9bc9-0911b0897e64.png">

1) Remover o número 3 (primeiro caractere)

2) Separar a string em duas, utilizando a vírgula como separador

3) Criar uma nova string com: (i) segunda string, (ii) espaço " ", (iii) primeira string

```
# Código em R (caso ajude a escrever o código em POSTGIS):

data %>%
  dplyr::mutate(log2 = stringr::str_sub(logradouro, 3)) %>% # 1.
  tidyr::separate(log2, into=c("log3", "log4"), sep=",") %>% #2.
  dplyr::mutate(log3 = dplyr::if_else(is.na(log3), "", log3),
         log4 = dplyr::if_else(is.na(log4), "", log4),
         log3 = stringr::str_trim(log3), #3.
         log4 = stringr::str_trim(log4), #3.
         log5 = base::paste0(log4, " ", log3)) %>% #4.
  dplyr::select(id, log3, log4, log5) %>%
  dplyr::rename(logradouro = log5)
```

**Comment by 0e1** [comment]
Formar string é tranquilo.

Mas, tem algo estranho nesse make_conf. Existem dois layer parcel.

Ainda, acho que vai demandar o desenvolvimento do uso de `sql_view` quando for um array em `orig_filename` para o caso de `method: geojson2sql`. Se não ingestar o `'LOTES_RURAIS'`, não precisa desenvolver.

**Comment by 0e1** [comment]
> Mas, tem algo estranho nesse make_conf. Existem dois layer parcel.

@IgorEliezer ou @crebollobr, por favor avaliaem a situação de [BR-RS-Bage/_pk0082.01](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/Bage/_pk0082.01). O _make_conf_ possui duas camadas _parcel_.

**Comment by crebollobr** [comment]
Agora só está fazer ingestão dos lotes urbanos, não tem suporte de software para fazer um join nos arquivos, logo faço o procedimento completo de ingestão

**Comment by IgorEliezer** [comment]
Só para registro: o material de Bagé foi baixado de https://github.com/GGC-Bage/GeoDataBase (per package.csv). Não encontrei licença lá nem no site da prefeitura.

O site "oficial" do geo de Bagé é https://sites.google.com/site/ggcbage/home, nem este tem licença.

**Comment by crebollobr** [comment]
Acredito que já terminamos essa issue
