### ISSUE TITLE
Categorias, tag e string de atribuição default

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv-BR#147]
Tomando como exemplo https://addressforall.maps.arcgis.com/home/item.html?id=7071ea4c9a284addb8c827c22aaebe0d, na lateral direita, temos os metadados _Categories_, _Tags_ e _Credits (Attribution)_:

![screen](https://github.com/digital-guard/preserv-BR/assets/41844788/2147dc13-6aad-47f1-b3ae-e16303a1b34d)

Todos eles podem ser manipulados via API. Podendo, então, serem padronizados conforme o tipo de _layer_.

Discutir nessa issue os valores padronizados para cada um desses metadados considerando ainda os diferentes tipos de _layers_.

Outra questões:

- Em _Terms of Use_ é usado _city hall_. Nem sempre doadores de dados são prefeituras. Não seria necessário uma tabela de correspondência **en <-> pt-br** (exemplo: city hall, prefeitura municipal)?
- Em _Terms of Use_ é usado _Provided by the city hall (Prefeitura Municipal de Natal) for OpenStreetMap_. Nos metadados https://git.digital-guard.org/preserv-BR/tree/main/data/RN/Natal/_pk0073.0 ou em [donatedPack](https://github.com/digital-guard/preserv-BR/blob/main/data/donatedPack.csv#L75) não existe algo que justifique o _for OpenStreetMap_. _for OpenStreetMap_ é necessário?

**Comment by IgorEliezer** [comment]
@0e1 

> Em Terms of Use é usado city hall. Nem sempre doadores de dados são prefeituras. Não seria necessário uma tabela de correspondência en <-> pt-br (exemplo: city hall, prefeitura municipal)?

De fato não temos uma coluna que classifique o tipo de entidade doadora  (e.g. "city hall", "state owned company", "company", etc.). Não sei se é possível levantar isso e adicionar uma coluna disso. Pelo menos o wikidata dá o tipo de entidade pelo P31.

Soluções:

1) Concatenar "Provided by the " + {entity_type}  + "(" {entity_name} + ").....
 1.a) O {entity_type} é dado por uma coluna de dados vindo do wikidata, ou...
 1.b) Faz-se um parse em "legalName" do doador em donor.csv. Se começar com "Prefeitura*", então o {entity_type} deverá ser "city hall". Caso contrário, usar "entity" como fallback/default, ou talvez outros tipos que dê para fazer um parse.

2) Mais simples. Concatenar "Provided by the " + {entity_name}.......

Agora, é mesmo necessário que apareça o tipo de entidade no "Terms of Use"? Sou da opinião de deixar mais simples o possível. Qualquer coisa a pessoa clica no link adicionado em {entity_type}. (@ppKrauss ?)

**Comment by 0e1** [comment]
> É necessário. É de interesse da ESRI que estes dados estejam disponíveis para a comudade OSM fazer uso. E mais ainda, os emails enviados por nós aos doadores é escrito mesmo que estes dados estariam disponíveis para o OSM.

Mas apesar de citar o OpenStreetMap nos emails os dados foram _disponibilizados para a A4A_ em, de forma implícita, domínio público. A _A4A processou_ os dados (ingestão), _manteve em domínio público_ (poderia licenciar de outra forma se quisesse) e _disponibilizou_ no ArcGis online.

Os termos de uso, então, devem se referir aos dados processados pela A4A e que estão disponibilizados na plataforma e não aos dados originais. Eu penso que os termos de uso deveriam ser simples para evitar confusão. Minha sugestão é usar **licensed under the CC0 1.0 Universal (CC0 1.0) license** apenas.

Se for necessário informar a forma como foi inferida a licença original dos dados (que está ou estará no metadados no git) eu usaria a descrição, logo após o trecho _The data was made available by Prefeitura Municipal de Natal_ .

Para comunidade OSM o importante é que o licenciamento dos dados que estão no arcgis seja compatível com a odbl.

Da forma como está escrito, os termos de uso se referem aos dados originais. Alguém interessado em reusar o que vê no arcgis poderá ficar confuso ao ler os termos. Pelo seguinte: está escrito que os dados foram doados pela prefeitura para o OSM (não está dito mas assumo que seja para fundação e que ela participou ativamente da doação) sob CC0,  mas a descrição informa que foram processados pela A4A. Já os créditos não citam o OSM. _Quais dados estou vendo no arcgis, original ou o processado? Qual a licença dos dados que estou vendo no arcgis? É igual a do original? Se o OSM participou por quê a licença dos dados processados não é Odbl?_

Já nos créditos (atribuição) eu usaria: **{nome oficial do doador}; AddresForAll**.

**Comment by 0e1** [comment]
@IgorEliezer Sabe a diferença entre **Categorias** e **tags**?

**Comment by ppKrauss** [comment]
Sobre as licenças, estamos preparando o site de resolução das mesmas, basta fornecer o link. Falta criar os "reports" das licenças municipais implícitas, que foi um texto trabalhado em separado e pendente de entrar no git.

https://github.com/digital-guard/licenses/issues/3

**Comment by IgorEliezer** [comment]
> @IgorEliezer Sabe a diferença entre **Categorias** e **tags**?

Categorias funcionam como pastas. Como categorias temos os países.

Tags são palavras-chaves e podem haver várias por camada. Acho interessante termos como tags, os tipos: `building, road, geoaddress, cityblock, parcel e boundary`; e `address` quando uma camada contiver endereços. Então um uma camada de building que tenha endereços teria as tags `building` e `address`. Uma camada de lotes com endereços: `parcel` e `address`.

**Comment by 0e1** [comment]
Exemplos de layer com metadados preenchidos via script.
Por favor, avaliem.

- https://addressforall.maps.arcgis.com/home/item.html?id=8f4a83dbd6a642d78f87e76677f7c346
- https://addressforall.maps.arcgis.com/home/item.html?id=c6e9a1b6934447259edd6fc88616c6b4
- https://addressforall.maps.arcgis.com/home/item.html?id=941c74249d03494486c29d13b0017533
- https://addressforall.maps.arcgis.com/home/item.html?id=7bbfb5299fb1481b982ee9e877bb5f3a
- https://addressforall.maps.arcgis.com/home/item.html?id=6142ffff6c0941fbbb19bdb5daefd37c
- https://addressforall.maps.arcgis.com/home/item.html?id=f0f74bb35b774174b9a7f392f5fe19aa

**Comment by 0e1** [comment]
Pergunta:

O endereço https://viz.addressforall.org/BR-AC-RioBranco/_pk0042.01/block deve redirecionar para o **map viewer** ou para a **página de metadados**? Atualmetne, redireciona para o **map viewer**.

**Comment by IgorEliezer** [comment]
> deve redirecionar para o **map viewer** ou para a **página de metadados**?

Melhor para o metadados, do contrário será meio inútil o público não ver.

**Comment by ppKrauss** [comment]
> Pergunta:
> 
> O endereço https://viz.addressforall.org/BR-AC-RioBranco/_pk0042.01/block deve redirecionar para o **map viewer** ou para a **página de metadados**? Atualmetne, redireciona para o **map viewer**.

Pergunta não procede, durante a definição do subdomínio `viz.addressforall.org` ficou definido que seria "VIZualização de dados", ou seja, link para o map view.  A questão aqui não é como usar um *endpoint* já definido, é como formatar um template, com um, dois ou mais links prioritários/chamativos... Neste caso, cabe primeiro ilustrar o contexto e o template.

**Comment by 0e1** [comment]
Considero issue encerrada. Se necessário, comentar em https://github.com/digital-guard/preserv/issues/147.
