### ISSUE TITLE
Planilhas colaborativas: erro de digitação e links

### ISSUE THREAD

**Issue by IgorEliezer** [digital-guard/preserv-BR#167]
Dois problemas no README do Brasil:

- [x] 1. Erro de digitação em "Planilhas colaborativ**f**as"
- [x] 2. O 1º link aponta para um doc que está na lixeira e marcada como suspeito.

![image](https://github.com/digital-guard/preserv-BR/assets/4673289/23b95afe-b31e-4ff9-be99-949deab0a5bc)

Em: https://github.com/digital-guard/preserv-BR/tree/main/data

**Comment by 0e1** [comment]
Fiz algumas correções em https://github.com/digital-guard/preserv-BR/commit/2d390f3a37989aba0315200ad063e8812b44dffe.

Removi _Planilhas colaborativas_ e adicionei ligações com as documentações de preenchimento de _donor_ e _donatedPack.csv_ em https://github.com/digital-guard/preserv-BR/commit/21a200f4bda519517655bad1c8489075908afafe.

Reparar que em _jurisdições_ adicionei a página https://wiki.addressforall.org/doc/dg:Guia_de_preenchimento_de_Planilha_jurisdictionLevel para servir de guia para preenchimento de _jurisdictionLevel*.csv_

**Comment by 0e1** [comment]
Se ainda encontrar problemas, relate.

**Comment by IgorEliezer** [comment]
Uma pergunta. Esta planilha https://github.com/digital-guard/preserv-BR/blob/main/data/donor.csv tem atualização periódica ou só quando é necessário? Andei fazendo algumas edições de melhoria nela.

**Comment by 0e1** [comment]
> Uma pergunta. Esta planilha https://github.com/digital-guard/preserv-BR/blob/main/data/donor.csv tem atualização periódica ou só quando é necessário? Andei fazendo algumas edições de melhoria nela.

1. Atualizar os dados do servidor a partir do csv faz parte do [workflow](https://wiki.addressforall.org/doc/dg:Workflow#Atualiza%C3%A7%C3%A3o_do_optim). Então, se o csv for atualizado no git, basta executar o procedimento;
2. donor.csv pode ser atualizado sempre que julgar necessário. Quanto mais atual melhor. Alterações desses dados só refletem se estiverem no git. 
3. Atualizar cada donor.csv a partir da planilha que você está mantendo não está ocorrendo (nem manualmente, nem automaticamente). Eu ainda não sei qual é o link da tabela pra poder automatizar ou atualizar manualmente (envie o link pra mim).
