### ISSUE TITLE
Arquivos de configuração com problemas

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv-BR#17]
Alguns problemas presentes nos arquivos de configuração:

1. CUS/Cusco/_pk001/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-PE/blob/main/data/CUS/Cusco/_pk001/make_conf.yaml): `method` de `address`;
2. SP/SaoBernardoCampo/_pk025/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/SaoBernardoCampo/_pk025/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/SP/SaoBernardoCampo/_pk025/make_conf.yaml): layers sem `method` e variável `codec`;
3. SP/Santos/_pk020/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Santos/_pk020/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/SP/Santos/_pk020/make_conf.yaml):  variável `codec`;
4. SP/Piracicaba/_pk045/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Piracicaba/_pk045/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/SP/Piracicaba/_pk045/make_conf.yaml): layers sem `method` e variável `codec`;
5. SC/Joinville/_pk038/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/SC/Joinville/_pk038/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/SC/Joinville/_pk038/make_conf.yaml): layers sem `method`;
6. RS/SantaMaria/_pk031/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/RS/SantaMaria/_pk031/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/RS/SantaMaria/_pk031/make_conf.yaml): layers sem `method`;
7. PR/Curitiba/_pk002/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/Curitiba/_pk002/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/PR/Curitiba/_pk002/make_conf.yaml): layers sem `method`;
8. MG/GovernadorValadares/_pk043/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/MG/GovernadorValadares/_pk043/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/MG/GovernadorValadares/_pk043/make_conf.yaml): layers sem `method` e variável `codec`;
9. MG/Contagem/_pk033/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/tree/main/data/MG/Contagem/_pk033/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/MG/Contagem/_pk033/make_conf.yaml): layers sem `method` e `srid` ou `srid_local` em layers;
10. PR/Araucaria/_pk067/make_conf.yaml: [atual](https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Araucaria/_pk067/make_conf.yaml)  [lixo](https://github.com/AddressForAll/LIXO-digital-preservation-BR/tree/master/data/in/PR/Araucaria/_pk067/make_conf.yaml): layer `nsvia` duplicado.

**Comment by crebollobr** [comment]
Problemas resolvidos ou abri issues individuais
