### ISSUE TITLE
SaoJoseCampos

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#170]
Verificar e publicar SaoJoseCampos

**Comment by crebollobr** [comment]
https://github.com/digital-guard/preserv-BR/issues/136

**Comment by crebollobr** [comment]
Pedir melhores dados para a prefeitura

**Comment by IgorEliezer** [comment]
> Pedir melhores dados para a prefeitura

Vi na planilha package que tem só eixos e bairros. Sem endereços.

Pode-se fazer um do seguinte:
* publicar o que tem como está e eu peço ao CRM contactar a prefeitura para fornecer material com endereço.
*  peço ao CRM contactar a prefeitura para fornecer material com endereço, e aguarda-se para publicar o conjunto todo.

(@ppKrauss o que você acha?)

**Comment by crebollobr** [comment]
bairros.zip
BAIRROS.shp
srid: 31983
bairro nsvia

logradouros.zip
LOGRADOUROS.shp
srid: 31983
nome via
ref

**Comment by crebollobr** [comment]
Feito, por favor testar

**Comment by IgorEliezer** [comment]
Readme = OK
Link VIZ nsvia = quebrado
Link VIZ via = quebrado
Imagem Evidências de teste = OK
