### ISSUE TITLE
Arquivos de Pato Branco

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#171]
Não localizei os arquivos de Pato Branco. Estão no sha256sum.txt mas não existem no servidor web.

ff5c05eeeeecd9fa6864d9613990d90e633689b11ae17e7711f6fa26fc76eb6a *PR-PatoBranco-tratamento.qgz
997f87581f28483fd8bf444e5d36a44787397c818d5b7795c551bebd1ece767c *README.md
9a4fdcdad356b7a1a0ecd12b53808cab4b91e13f8e5b87fe96d5d05b88ee5b4f *lotes.zip
dc0a46ccdce9a9723ef97ff7fac27dd4d6da92e5a0a231dea9df903ff61304ad *lotes_chacaras.zip
7c8109bc4686737ff08d4e5afc0a10ef0db26524a2629e3840361dda4bf0c700 *lotes_chacaras_num.zip
5985179b90eb5ea88f6bf6b94bde9030e9f748cca0595019087d2971908ff4d4 *lotes_num.zip
76e06e4a2dea198a44ca1fef89be6f5f6448fe3e3d7efa87d308fd214a20d4c0 *meio_fio.zip
4f086c0e3bbbac2d384f9f92759ab41fff998ece6b79ee83f854272386a58182 *quadra.png
77fa67d50ba037b2009fd0d46f2ed446e625bf37958e7e4243170720d61da969 *quadras_num.zip
9e2bd34eb8a2b65f1dd41bcdd7e0871272c299ab00eeca58a7a5fdba441fb8e6 *sha256sum.txt
5fa960eadfebc13e1e3b46c3b4b47f982b8aca58e810802428b4f75213fdb00a *Relatorio_de_numeracao_predial.zip

**Comment by 0e1** [comment]
Não existe make_conf no repositorio nesse momento: https://github.com/digital-guard/preserv-BR/tree/f9860c52c06c64ff921fa1af13323d23e23c6a87/data/PR/PatoBranco/_pk0037.01. Isso dificulta saber quais são os arquivos que devem ser preservados.

Se o processo de preservação foi realizado (gerar hash, subir arquivo pra nuvem, atualizar csv), basta fazer o download.

Dos arquivos que eu acho que devem ser preservados, todos estão a disposição para download:

- lotes.zip: http://dl.digital-guard.org/9a4fdcdad356b7a1a0ecd12b53808cab4b91e13f8e5b87fe96d5d05b88ee5b4f
- lotes_chacaras.zip: http://dl.digital-guard.org/dc0a46ccdce9a9723ef97ff7fac27dd4d6da92e5a0a231dea9df903ff61304ad
- lotes_chacaras_num.zip: http://dl.digital-guard.org/7c8109bc4686737ff08d4e5afc0a10ef0db26524a2629e3840361dda4bf0c700
- lotes_num.zip: http://dl.digital-guard.org/5985179b90eb5ea88f6bf6b94bde9030e9f748cca0595019087d2971908ff4d4
- meio_fio.zip: http://dl.digital-guard.org/76e06e4a2dea198a44ca1fef89be6f5f6448fe3e3d7efa87d308fd214a20d4c0
- quadras_num.zip: http://dl.digital-guard.org/77fa67d50ba037b2009fd0d46f2ed446e625bf37958e7e4243170720d61da969
- Relatorio_de_numeracao_predial.zip: http://dl.digital-guard.org/5fa960eadfebc13e1e3b46c3b4b47f982b8aca58e810802428b4f75213fdb00a

**Comment by crebollobr** [comment]
vou fechar essa issue, vamos pedir dados melhores para a prefeitura.
