### ISSUE TITLE
Pato Branco está faltando bairro para completar a cidade

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#173]
https://github.com/digital-guard/preservCutGeo-BR2021/blob/main/data/PR/PatoBranco/_pk0037.01/nsvia/pols_6g6.geojson

![image](https://github.com/digital-guard/preserv-BR/assets/22559999/43d222d3-08bb-4cfc-8aad-d13b2da18737)

**Comment by crebollobr** [comment]
Os polignos não estão fechados
{"error": "000000000010", "nsvia": "BAIRRO CENTRO"}
{"error": "000000000010", "nsvia": "BAIRRO JARDIM DAS AMERICAS"}
{"error": "000000000010", "nsvia": "BAIRRO SAO FRANCISCO"}

**Comment by 0e1** [comment]
Atualmente, as _features_ com _error_ não nulo não são publicadas no CutGeo, por isso o buraco.

Nessa situação, acho que o caminho seria solicitar a correção ao doador.

Aqui são discutidas novas diretrizes sobre publicação no cutgeo: https://github.com/digital-guard/preserv/issues/153

**Comment by crebollobr** [comment]
vou fechar essa issue, vamos pedir dados melhores para a prefeitura.
