### ISSUE TITLE
Como fazer via em Pato Branco

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#174]
As vias em pato Branco são faces de quadra em polígono ( ALINHAMENTO RUAS ) e pontos com o nome da via ( NOME DE RUAS )

https://github.com/digital-guard/preserv-BR/tree/main/data/PR/PatoBranco/_pk0037.01

arquivo 
462e42be91abea4d29e9c7af89c61a05523fbc535523b25f972402d5f2bd0fa1.zip

**Comment by crebollobr** [comment]
![image](https://github.com/digital-guard/preserv-BR/assets/22559999/c6790e32-8e7b-448d-ab48-b5dd6b8408cd)

**Comment by 0e1** [comment]
As linhas da camada _alinhamento de ruas_ provavelmente se referem ao meio-fio e não a testada dos lotes.

Não acho que seja impossível construir as vias (com nome) a partir dos meio-fio e de pontos com nome de ruas. Mas, certamente demandará tempo e talvez o resultado não seja muito bom. Por exemplo, poderíamos formar os eixos das vias ligando os pontos com mesmo nome (funcionaria para aquelas que tem mais de um ponto e podendo gerar vias mais curtas que a realidade.)

Minha sugestão é conversar, mostrar como deveria ser e tentar obter as vias como linhas e com nome do doador. Não acredito que não possuam os eixos das vias se possuem o alinhamento do meio-fio.

**Comment by IgorEliezer** [comment]
> ![image](https://user-images.githubusercontent.com/22559999/275350706-c6790e32-8e7b-448d-ab48-b5dd6b8408cd.png)

Isso está com cara que se originou de arquivo AutoCAD. Cada texto do CAD se transformou em um ponto com o texto. 

Que eu lembro o conjunto todo de arquivos deste doador era precário: as quadras, os lotes, etc. Parece que era tudo conversão do AutoCAD como ensaio para adotar o GIS.

Sugiro:
- Usar as ruas do OpenStreetMap. Talvez usar os pontos para verificar erro de denominação de ruas.
- Solicitar do doador novo pacote de dados. Mas, será que vale a pena? pois talvez o estado do dados deles não mudou muito.

**Comment by IgorEliezer** [comment]
Sugiro o fechamento desta issue, visto que foi solicitado da prefeitura fornecer dados novos e melhores: https://github.com/digital-guard/preserv-BR/issues/110#issuecomment-1780078059
