### ISSUE TITLE
Corrigir a imagem da evidência de teste em CE-Fortaleza

### ISSUE THREAD

**Issue by IgorEliezer** [digital-guard/preserv-BR#180]
Simples, a imagem em [Evidências de teste](https://github.com/digital-guard/preserv-BR/tree/main/data/CE/Fortaleza/_pk0097.01#evid%C3%AAncias-de-teste) está quebrada.

Caso precisar, posso gerar uma nova.

**Comment by 0e1** [comment]
Gere uma nova imagem. A principio, basta commitar a nova imagem.

**Comment by IgorEliezer** [comment]
Pronto. https://github.com/digital-guard/preserv-BR/commit/af197087d22c0923bc8431a86dd8c1411bf3bf3d
