### ISSUE TITLE
Voltar a opção codec nos templates 

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#20]
Alguns shapefiles foram feitos em latin1 ou outra codificação.
Nos históricos dos templates vai ter essa implementação  YAML

`codec: -W iso-8859-1`

* [preserv-BR/data/SP/Santos/_pk020/make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Santos/_pk020/make_conf.yaml)

* [preserv-BR/data/SP/SaoBernardoCampo/_pk025/make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoBernardoCampo/_pk025/make_conf.yaml)

* [preserv-BR/data/SP/Piracicaba/_pk045/make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/Piracicaba/_pk045/make_conf.yaml)

* [preserv-BR/data/MG/GovernadorValadares/_pk043/make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/MG/GovernadorValadares/_pk043/make_conf.yaml)

**Comment by ppKrauss** [comment]
@crebollobr  precisamos de mais informação e uma explicação mais didática para quem for analisar e corrigir o problema.

Os  makefiles desses casos ilustrados gerados hoje pela versão atual do `make me` rodando com python e templates mais recentes, **está com falha**?

A solicitação de "voltar a opção cedec" é para quais casos (visto que nos links não precisa voltar nada, precisa?)

**Comment by crebollobr** [comment]
Alguns shapefiles estão codificados em latin1 ou outra codificação.
o comando shp2pgsql precisa que seja explicitado a codificação para funionar
Por isso é usado a variavel codec, exemplos nos links acima

**Comment by ppKrauss** [comment]
Oi @crebollobr  entendo que é redundante ter `codec` e `method_opts` simultaneamente, e optamos por adotar apenas a  `method_opts`... A princípio é o contrário, deveríamos eliminar todas as ocorrências de `codec`.

-----

PS1: repare que  `method_opts: -W latin1`  = `method_opts: -W iso-8859-1`.

PS2: no futuro poderemos retomar com o Claiton a discussão do que seria melhor fazer, incluir automaticamente a option do comando  `shp2pgsql -W $codec` quando existir `codec` configurado, ou manter o uso de `method_opts`...  O uso do *codec* certamente é mais elegante e amigável para o usuário final do YAML, mas o template makefile fica mais simples usando apenas  `method_opts`, para esta e outras necessidades.

**Comment by ppKrauss** [comment]
@0e1  precisamos aposentar o `csv_enconding` e usar o genérico `codec`. Nos casos onde havia `method_opts` exclusivamente para isso, eliminar, senão adaptar para garantir que `codec`  seja implementado como expansão interna (parser) de `method_opts`.

O exemplo abaixo ajudou a tomar a decisão, precisamos mesmo de um descritor de tipo mais robusto e mais específico do que a extensão do arquivo.

-----

Exemplo de [preserv-BR/RS/CaxiasSul](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/CaxiasSul/_pk075/make_conf.yaml): 

```yaml
address:
    subtype: cmpl
    method: csv2sql
    csv_encoding: us-ascii
    p: 5a
    file: 5
    sql_select: ['cod_localizacao_completo', 'nr_imovel AS house_number']
    orig_filename: data-1626873935092
``` 

----

O termo `codec`  (ver [lista na Wikipedia](https://en.wikipedia.org/wiki/List_of_codecs))  lembra mais MIME-Type do que *endode*, ainda assim é razoável, desde que possamos fornecer a nossa interpretação padronizada:

Extensão | Variante | **`codec`**  sugerido 
-------------|----------------------|----------------------
CSV  | default |  `text/csv;charset=UTF-8`
CSV  | Latin1 |  `text/csv;charset=ISO-8859-1`
CSV  | MS-Windows |  `text/csv;charset=Windows-1252`
CSV  | ASCII |  `text/csv;charset=us-ascii`
CSV  | ponto-e-virgula |  `text/csv;charset=UTF-8;delimiter=%3B`
CSV.ZIP  | default |  `application/zip;content=text/csv;charset=UTF-8`
CSV.GZ  | default |  `application/gzip;content=text/csv;charset=UTF-8`
GeoJSON | default | `application/geo+json;charset=UTF-8`
GeoJSON.GZ | default | `application/gzip;content=application/geo+json;charset=UTF-8`
SHP.ZIP | default | `application/zip;content=x-gis/x-shapefile`
TSV  | CSV com Tab |  `text/csv;charset=UTF-8;delimiter=%09`
...|...|...

A sugestão portanto é que haja um interpretador de `codec`, fazendo pelo menos um *split* dele em nomes de variável mais longas e complexas que possam ser usadas pelo Mustache, por exemplo `codec_charset`, `codec_mimeMain`, `codec_content`.. Lembrando que:

* todos são *content* exceto quando surge content no subtipo aí o tipo se torna mimeMain
* arquivos de preservação são sempre comprimidos conforme extensão, de modo que a indicação de ZIP ou GZ ou outro no `codec` seria indicador de que devemos fazer uma segunda descompactação.

**Comment by ppKrauss** [comment]
> @0e1 precisamos aposentar o `csv_enconding` e usar o genérico `codec`. Nos casos onde havia `method_opts` exclusivamente para isso, eliminar, senão adaptar para garantir que `codec` seja implementado como expansão interna (parser) de `method_opts`.
> 
> O exemplo abaixo ajudou a tomar a decisão, precisamos mesmo de um descritor de tipo mais robusto e mais específico do que a extensão do arquivo.
> 
> A [_issue_ 22 de preserv](https://github.com/digital-guard/preserv/issues/22) **é pré-requisto** para esta implementação, tendo em vista que já começaria a elevar a complexidade e a demanda por dados de controle durante o processamento de templates.
> 
> Exemplo de [preserv-BR/RS/CaxiasSul](https://github.com/digital-guard/preserv-BR/blob/main/data/RS/CaxiasSul/_pk075/make_conf.yaml):
> 
> ```yaml
> address:
>     subtype: cmpl
>     method: csv2sql
>     csv_encoding: us-ascii
> ```
> 
> O termo `codec` (ver [lista na Wikipedia](https://en.wikipedia.org/wiki/List_of_codecs)) lembra mais MIME-Type do que _endode_, ainda assim é razoável, desde que possamos fornecer a nossa interpretação padronizada:
> Extensão 	Variante 	**`codec`** sugerido
> CSV 	default 	`text/csv;charset=UTF-8`
> CSV 	Latin1 	`text/csv;charset=ISO-8859-1`
> CSV 	MS-Windows 	`text/csv;charset=Windows-1252`
> CSV 	ASCII 	`text/csv;charset=us-ascii`
> CSV 	ponto-e-virgula 	`text/csv;charset=UTF-8;delimiter=%3B`
> CSV.ZIP 	default 	`application/zip;content=text/csv;charset=UTF-8`
> CSV.GZ 	default 	`application/gzip;content=text/csv;charset=UTF-8`
> GeoJSON 	default 	`application/geo+json;charset=UTF-8`
> GeoJSON.GZ 	default 	`application/gzip;content=application/geo+json;charset=UTF-8`
> SHP.ZIP 	default 	`application/zip;content=x-gis/x-shapefile`
> TSV 	CSV com Tab 	`text/csv;charset=UTF-8;delimiter=%09`
> ... 	... 	...
> 
> A sugestão portanto é que haja um interpretador de `codec`, fazendo pelo menos um _split_ dele em nomes de variável mais longas e complexas que possam ser usadas pelo Mustache, por exemplo `codec_charset`, `codec_mimeMain`, `codec_content`.. Lembrando que:
> 
>     * todos são _content_ exceto quando surge content no subtipo aí o tipo se torna mimeMain
> 
>     * arquivos de preservação são sempre comprimidos conforme extensão, de modo que a indicação de ZIP ou GZ ou outro no `codec` seria indicador de que devemos fazer uma segunda descompactação.
> 
> 
> PS: @0e1 , como vamos refatorar todos os YAMLs, já aproveitamos para mudar alguns nomes ruins, por exemplo `query_view` precisa mudar para `sql_view`, para ficar consistente com `sql_select`.

@0e1 estamos aguardando.

**Comment by ppKrauss** [comment]
Pré-requisito https://github.com/digital-guard/preserv/issues/22
