### ISSUE TITLE
Caxias do Sul, genericvia

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#26]
Outro problema:
Comentário no make_conf.yaml de Caxias do Sul solicita join entre genericvia e cadgenericvia:

*  join genericvia:inscrica_1 == cadgenericvia:cod_localizacao_completo

No entanto, não existe o layer cadgenericvia.

**Comment by ppKrauss** [comment]
@crebollobr favor conferir se procede: uma  *genericvia* (ferrovia, hidrovia, etc.) não tem outra utilidade senão o traçado de quadras, portanto não se podem exigir dados cadastrais de endereço deste layer.

**Comment by crebollobr** [comment]
Não foi possível testar makefile travando
