### ISSUE TITLE
Nomear o Carlos como "testador" natural, oficial das aplicações feitas pelo Claiton

### ISSUE THREAD

**Issue by ThierryAJean** [digital-guard/preserv-BR#28]

**Comment by ppKrauss** [comment]
@Carlos e @0e1 , a dinâmica é:
1. Clainton atualiza ou desenvolve software
2. Carlos testa
3. Carlos fecha issue relativa ao *bug* ou *enhancement*

Qualquer um dos dois pode FECHAR essa issue depois que alinhados

**Comment by crebollobr** [comment]
Colocar Testar @crebollobr no comentário da issue
