### ISSUE TITLE
Verificar importação git novo

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#31]
Verificar se todos os arquivos do git antigo vieram para o novo.

Vários diretórios não estão completos, parar e verificar

**Comment by ppKrauss** [comment]
@crebollobr  por favor listar aqui os casos que desconfia.  @0e1 ajude o Carlos

**Comment by crebollobr** [comment]
NOK _pk010 /opt/carlos/preserv-BR/data/SP/Itu/_pk010
NOK _pk036 ./data/in/SP/Atibaia/_pk036
NOK _pk023 /opt/carlos/preserv-BR/data/ES/Vitoria/_pk023
NOK _pk019 ./data/in/PR/SaoJosePinhais/_pk019
