### ISSUE TITLE
Ingestão de Niterói

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#36]
Atualizar todos os arquivos de Niterói com a nova remessa

**Comment by crebollobr** [comment]
Aguardar a resposta da prefeitura sobre muitos zeros no campo numero predial

**Comment by crebollobr** [comment]
Alguma novidade?

**Comment by luisfelipebr** [comment]
> Alguma novidade?

Se colocaram zero no numero predial é porque o número predial ainda não foi mapeado... não faz sentido contatar a prefeitura sobre isso. Mas o arquivo de lotes foi atualizado no portal de dados abertos, vou subir para o servidor e atualizar os demais arquivos (sha256sum, README, yaml)

**Comment by luisfelipebr** [comment]
Atualizei o arquivo de lotes (no sha256sum), os outros arquivos não vão mudar. Pode fazer a ingestão, mesmo com tantos endereços faltantes
