### ISSUE TITLE
Make deixa de copiar README antigo

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#42]
A falha é grave pois perde-se o README bom, por exemplo em `/data/MG/BeloHorizonte/_pk012` ao rodar `make` .

Novo comportamento a implementar: gerar `README-draft.md` com o software, sobrepondo o draft antigo se existir. `README.md` permanece inalterado.

PS: resolver junto com #41

**Comment by 0e1** [comment]
Resolvido em todas as jurisdições existentes atualmente, por exemplo: https://github.com/digital-guard/preserv-PE/commit/31da8b4e5f76bf99ebfa7a7a493dfb5535b84a88
