### ISSUE TITLE
Tratar os dados de Toledo

### ISSUE THREAD

**Issue by ThierryAJean** [digital-guard/preserv-BR#45]
22/06/21: Igor analisa 1º envio, via email. O material consiste de: Eixos, quadras, loteamentos, bairros, limite de município e pontos de equipamentos urbanos. Não há lotes ou pontos contendo endereços.
13/10/21: Igor analisa. O material é útil e contém endereços, mas requer tratamento. Pontos de endereço contém o número predial mas não há nome de logradouro. Ver coluna "O que fazer."
22/11/21: Luis analisa. Encaminharam numero do lote, mas essa informação é irrelevante, visto que não possuímos base geoespacial de lotes. Luis acredita que os dados recebidos anteriormente são suficientes.

Precisamos fazer um cruzamento dos dados que temos para fazer uma base.

**Comment by crebollobr** [comment]
Adicionar a empreitada #80
