### ISSUE TITLE
Workflow da edição de planilhas 

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#54]
Os arquivos CSV do Github  infelizmente não são amigavelmente editáveis. Algumas planilhas todavia são ainda dependentes da interface humana nas primeiras etapas do *workflow* do trabalho, ao dar entrada em um novo *donor*  ou *donatedPack*. Este é o passo-a-passo a ser seguido:

1. [Editar a planilha colaborativa amigável](https://docs.google.com/spreadsheets/d/1-FQjjhHjJnAOxSWYEdFU_RePxAJDsJCnLviOyDo3QMM/edit#gid=815577163);
2. Baixar e normalizar com `make getEdits` ou os comandos  `curl` do  *target* (ver exemplo)
4. fazer `git diff -wb` para conferir.
5. se tudo ok fazer `git pull`,  `git add`, commit e push.

-----

## Exemplo
```sh
cd preserv-BR/data/

curl "https://docs.google.com/spreadsheets/d/1-FQjjhHjJnAOxSWYEdFU_RePxAJDsJCnLviOyDo3QMM/gviz/tq?tqx=out:csv&gid=815577163" \
   | csvformat > donor.csv
git diff -wb donor.csv

curl "https://docs.google.com/spreadsheets/d/1-FQjjhHjJnAOxSWYEdFU_RePxAJDsJCnLviOyDo3QMM/gviz/tq?tqx=out:csv&gid=42455849" \
  | csvformat > donatedPack.csv
git diff -wb donatedPack.csv
```

A solução CSVkit requer instalar, `sudo pip install csvkit`, que instala também o comando `csvformat`. 

PS1: conforme [discutido](https://superuser.com/a/1692737/276588) API do  Gogle está baixando com um monte de aspas, diferente do download direto da interface. Uma  solução seria baixar manualmente... O melhor é normalizar. No futuro o comando `frictionless` talvez incorpore a normalização. Sugiro incluir normalização UTF8 que usamos no PostgreSQL. 

PS2: o google/spreadsheets também oferece opção de sql_query na API, o que permite descartar os campos de cache da planilha donatedPack... [ver aqui](https://developers.google.com/chart/interactive/docs/dev/implementing_data_source#request-format).

**Comment by 0e1** [comment]
Conteúdo migrado para https://wiki.addressforall.org/doc/dg:Workflow#Outros.
