### ISSUE TITLE
Implementar o novo esquema de identificação de pacotes

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#55]
Conforme diretiva geral (para todos os países), [preserv/issues/40](https://github.com/digital-guard/preserv/issues/40), os identificadores estão sendo adaptados. Conforme  #54  o workflow recebe essa nova diretiva primeiramente nas planilhas online (google-spreadsheets), em seguida os arquivos CSV do git.

IMPACTO: demanda ainda fazer refatoração de todas as pastas, e ter função que formate adequadamente os indentificadores, que no repositório terão a forma `pk_DDDD.CC`, com Donor_id e Counter_pack em destaque. 

Ver https://github.com/digital-guard/preserv-BR/blob/main/data/donatedPack-old2new.csv

**Comment by 0e1** [comment]
git mv _pk001 _pk0001.01
git mv _pk053 _pk0001.02
git mv _pk056 _pk0001.03
git mv PR/Curitiba/_pk002 PR/Curitiba/_pk0002.01
git mv _pk004 _pk0003.01
git mv _pk007 _pk0004.01
git mv _pk051 _pk0004.01
git mv ES/Serra/_pk022 ES/Serra/_pk0005.01
git mv ES/Vitoria/_pk023 ES/Vitoria/_pk0006.01
git mv ES/VilaVelha/_pk024 ES/VilaVelha/_pk0007.01
git mv MG/BeloHorizonte/_pk012 MG/BeloHorizonte/_pk0008.01
git mv MG/Contagem/_pk033 MG/Contagem/_pk0009.01
git mv PE/Recife/_pk021 PE/Recife/_pk0010.01
git mv PR/Cascavel/_pk016 PR/Cascavel/_pk0011.01
git mv PR/MarechalCandidoRondon/_pk030 PR/MarechalCandidoRondon/_pk0013.01
git mv PR/Pinhais/_pk029 PR/Pinhais/_pk0014.01
git mv PR/SaoJosePinhais/_pk019 PR/SaoJosePinhais/_pk0015.01
git mv RJ/Niteroi/_pk018 RJ/Niteroi/_pk0016.01
git mv RS/Gravatai/_pk014 RS/Gravatai/_pk0017.01
git mv RS/PortoAlegre/_pk027 RS/PortoAlegre/_pk0018.01
git mv RS/SantaMaria/_pk031 RS/SantaMaria/_pk0019.01
git mv SC/JaraguaSul/_pk034 SC/JaraguaSul/_pk0020.01
git mv SP/Atibaia/_pk036 SP/Atibaia/_pk0021.01
git mv SP/Campinas/_pk039 SP/Campinas/_pk0022.01
git mv SP/GRJ/_pk052 SP/GRJ/_pk0023.01
git mv SP/Itu/_pk010 SP/Itu/_pk0024.01
git mv SP/Jundiai/_pk028 SP/Jundiai/_pk0025.01
git mv SP/Limeira/_pk015 SP/Limeira/_pk0026.01
git mv SP/LaranjalPaulista/_pk032 SP/LaranjalPaulista/_pk0027.01
git mv SP/Osasco/_pk026 SP/Osasco/_pk0028.01
git mv SP/Santos/_pk020 SP/Santos/_pk0029.01
git mv SP/SaoBernardoCampo/_pk025 SP/SaoBernardoCampo/_pk0030.01
git mv SP/Sorocaba/_pk017 SP/Sorocaba/_pk0031.01
git mv SP/SaoVicente/_pk013 SP/SaoVicente/_pk0032.01
git mv SP/SaoPaulo/_pk035 SP/SaoPaulo/_pk0033.01
git mv MS/CampoGrande/_pk037 MS/CampoGrande/_pk0034.01
git mv SC/Joinville/_pk038 SC/Joinville/_pk0035.01
git mv SP/Salto/_pk040 SP/Salto/_pk0036.01
git mv PR/PatoBranco/_pk041 PR/PatoBranco/_pk0037.01
git mv RJ/DuqueCaxias/_pk042 RJ/DuqueCaxias/_pk0038.01
git mv MG/GovernadorValadares/_pk043 MG/GovernadorValadares/_pk0039.01
git mv SP/Cabreuva/_pk044 SP/Cabreuva/_pk0040.01
git mv SP/Piracicaba/_pk045 SP/Piracicaba/_pk0041.01
git mv AC/RioBranco/_pk046 AC/RioBranco/_pk0042.01
git mv SP/SaoJoseCampos/_pk047 SP/SaoJoseCampos/_pk0043.01
git mv _pk009 _pk0044.01
git mv PI/Teresina/_pk048 PI/Teresina/_pk0045.01
git mv _pk049 _pk0046.01
git mv _pk050 _pk0047.01
git mv MS/Dourados/_pk054 MS/Dourados/_pk0048.01
git mv SP/Cerquilho/_pk055 SP/Cerquilho/_pk0049.01
git mv _pk057 _pk0051.01
git mv SP/RibeiraoPreto/_pk058 SP/RibeiraoPreto/_pk0052.01
git mv SC/Florianopolis/_pk059 SC/Florianopolis/_pk0053.01
git mv GO/Goiania/_pk060 GO/Goiania/_pk0054.01
git mv MG/Uberaba/_pk061 MG/Uberaba/_pk0055.01
git mv PE/Caruaru/_pk062 PE/Caruaru/_pk0056.01
git mv MG/Uberlandia/_pk063 MG/Uberlandia/_pk0057.01
git mv SP/Itanhaem/_pk064 SP/Itanhaem/_pk0058.01
git mv PR/_pk065 PR/_pk0059.01
git mv PE/Petrolina/_pk066 PE/Petrolina/_pk0060.01
git mv PR/Araucaria/_pk067 PR/Araucaria/_pk0061.01
git mv RO/JiParana/_pk068 RO/JiParana/_pk0062.01
git mv RS/NovoHamburgo/_pk069 RS/NovoHamburgo/_pk0063.01
git mv RS/SantaCruzSul/_pk070 RS/SantaCruzSul/_pk0064.01
git mv SP/Cubatao/_pk071 SP/Cubatao/_pk0065.01
git mv PE/Bezerros/_pk072 PE/Bezerros/_pk0066.01
git mv SP/Paulinia/_pk073 SP/Paulinia/_pk0067.01
git mv DF/Brasilia/_pk074 DF/Brasilia/_pk0068.01
git mv RS/CaxiasSul/_pk075 RS/CaxiasSul/_pk0069.01
git mv MG/Itabira/_pk076 MG/Itabira/_pk0070.01
git mv AM/Manaus/_pk077 AM/Manaus/_pk0071.01
git mv PB/JoaoPessoa/_pk078 PB/JoaoPessoa/_pk0072.01
git mv RN/Natal/_pk079 RN/Natal/_pk0073.01
git mv RN/SaoGoncaloAmarante/_pk080 RN/SaoGoncaloAmarante/_pk0074.01
git mv SC/Brusque/_pk081 SC/Brusque/_pk0075.01
git mv RS/Canoas/_pk082 RS/Canoas/_pk0076.01
git mv SC/Chapeco/_pk083 SC/Chapeco/_pk0077.01
git mv RJ/RioJaneiro/_pk084 RJ/RioJaneiro/_pk0078.01
git mv PR/Toledo/_pk085 PR/Toledo/_pk0079.01

**Comment by 0e1** [comment]
Já implementado.
