### ISSUE TITLE
Documentar templates e tplInputSchemas

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#6]
Agora que existe mais de um e são previstos mais alguns, cabe destacar principalmente as diferenças entre um template e outro, ou entre um tplInputSchema_id e outro.

Como temos agora o subdomínio docs com conteúdo publicado pelo  [documentation_generator](http://docs.addressforall.org/documentation_generator/pt/), já podemos também começar a organizar a documentação no /docs, bem como registrar exemplos de makefile por lá.

@crebollobr e @cchness favor comentar abaixo sugestões de exemplo (pk) e de teor para a documentação.

**Comment by crebollobr** [comment]
RJ/Niteroi/_pk018/make_conf.yaml 
- Join
- XLXS

/data/PE/Recife/_pk021/make_conf.yaml
- method_opts:

./data/SP/SaoPaulo/_pk035/make_conf.yaml
- Make com loop

./data/MG/BeloHorizonte/_pk012/make_conf.yaml
- cvs

./data/PR/Pinhais/_pk029/make_conf.yaml
- query_view

./data/SP/Itu
- ogr2ogr ( importar do Lixo )

**Comment by ppKrauss** [comment]
@crebollobr , é preciso editar no /docs

**Comment by crebollobr** [comment]
Qual o caminho do /doc para makefiles?

**Comment by crebollobr** [comment]
Acho que a documentação está seguindo fora dessa issue
