### ISSUE TITLE
Ingestão de dados - Rio de Janeiro

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv-BR#60]
(Issue sem descrição @luisfelipebr favor sempre descrever)

**Comment by ppKrauss** [comment]
? como ficou isso, @crebollobr ?

**Comment by crebollobr** [comment]
A prioridade era publicar os dados, volto essa semana a criar novos makefiles

**Comment by crebollobr** [comment]
https://github.com/digital-guard/preserv/issues/104

**Comment by crebollobr** [comment]
#80

**Comment by crebollobr** [comment]
Incorporara #80
