### ISSUE TITLE
Publicar tudo do preserv-BR no preservCutGeo-BR2021

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#66]
Publicar em [preservCutGeo-BR2021](https://github.com/digital-guard/preservCutGeo-BR2021) seguindo as instruções do @0e1 por hora disponiveis na [Wiki](https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo). 

- [x]  Listar aqui nos comments a listagem de todos os pacotes  [daqui](https://github.com/digital-guard/preserv-BR/tree/main/data) com makefile.

- [x] Publicar na sequência todos os layers
- [x] Indicar e explicar cada layer ou pacote que deixar de publiacar

**Comment by crebollobr** [comment]
Na pasta /var/gits/_dg/preserv-BR/data/_pk0004.01
ingest20 novo
make me pg_db=ingest20
make all_layers pg_db=ingest20
make publicating_geojsons_via pg_db=ingest20



carlos@addressforall:/var/gits/_dg/preserv-BR/data/_pk0004.01$ make publicating_geojsons_via pg_db=ingest20
mkdir -m777 -p /var/gits/_dg/preservCutGeo-BR2021/data/_pk0004.02/via
--- Gerando arquivos em /var/gits/_dg/preservCutGeo-BR2021/data/_pk0004.02/via ---
psql postgres://postgres@localhost/ingest20 -c "SELECT ingest.publicating_geojsons('via','BR','/var/gits/_dg/preservCutGeo-BR2021/data/_pk0004.02/via','1');"
ERROR:  cannot call jsonb_each on a non-object
CONTEXT:  SQL statement "
          WITH t AS ( SELECT * FROM hcode_distribution_reduce_pre_raw('null'::jsonB, 1, 0, 100000, 2097152) )

            SELECT hcode,
                   SUM(n_items)::int AS n_items,
                   round(AVG(mdn_items))::int AS mdn_items,
                   SUM(n_keys)::int AS n_keys,
                   NULL::jsonB as j
            FROM (
              -- Accepted rows:
              SELECT  *
              FROM t
              WHERE t.j IS NULL AND (100000 IS NULL OR n_items>=100000)

              UNION ALL

              -- Erode more (but can fail with no p_threshold_sum backtrack) and joins with accepted rows:
              SELECT *
              FROM hcode_distribution_reduce_recursive_raw(
                ( SELECT jsonb_object_agg(hcode,n_items) FROM t WHERE t.j IS NULL AND n_items<100000 ),
                  1,                            0,                      100000,                         2097152   , 3, (1+1)::smallint
              )

              UNION ALL

              -- Backtracking non-accepted rows:
                    SELECT q.* FROM t,
                     LATERAL (   SELECT * FROM hcode_distribution_reduce_recursive_raw( t.j,   1,                            0,                      100000,                         2097152   , 3, (1+1)::smallint )   ) q
                    WHERE t.j IS NOT NULL
            ) t2
            GROUP BY hcode ORDER BY hcode
         "
PL/pgSQL function hcode_distribution_reduce_recursive_raw(jsonb,integer,integer,integer,integer,integer,smallint) line 38 at RETURN QUERY
SQL function "hcode_distribution_reduce_recursive_raw" statement 1
SQL function "publicating_geojsons_p3" statement 2
SQL function "publicating_geojsons" statement 3
SQL function "publicating_geojsons" statement 1
make: *** [makefile:166: publicating_geojsons_via] Error 1

**Comment by crebollobr** [comment]
Na pasta /var/gits/_dg/preserv-BR/data/_pk0004.03
make me pg_db=ingest20
make all_layers pg_db=ingest20




------------------------------------------
------ Layer tipo via_full  ------
-- Incluindo dados do arquivo-1 do package-7600000403101 na base ingest20 --
 Nome-hash do arquivo-1: befb1a28910b56920b7c10b7ae1a25d5d32f1b13931463076adebc4ab33db114.pbf
 Tabela do layer: pk7600000403101_p1_via
 Sub-arquivos do arquivo-1 com o conteúdo alvo: *brazil-latest.osm.pbf*
 Tema dos sub-arquivos: Dados OpenStreetMap
Run with tmux and sudo! (DANGER: seems not idempotent on psql)
carlos
Above user is root? If not, you have permissions for all paths?
[Press ENTER to continue or Ctrl+C to quit]
psql postgres://postgres@localhost/ingest20 -c "DROP TABLE IF EXISTS pk7600000403101_p1_via CASCADE"
NOTICE:  table "pk7600000403101_p1_via" does not exist, skipping
DROP TABLE
Copying ....
cd /tmp/sandbox/_pkBR43_001; cp /var/www/preserv.addressforall.org/download/befb1a28910b56920b7c10b7ae1a25d5d32f1b13931463076adebc4ab33db114.pbf "brazil-latest.osm.pbf.pbf" ; chmod -R a+rwx . > /dev/null
Conferindo se SRID 4326 está configurado:
 srid |              proj4text               
------+--------------------------------------
 4326 | +proj=longlat +datum=WGS84 +no_defs 
(1 row)

[Press ENTER to continue or Ctrl+C to quit]
Executando osm2sql ...
psql postgres://postgres@localhost/ingest20 -c "CREATE VIEW vw1_pk7600000403101_p1_via AS SELECT way, tags FROM jplanet_osm_roads WHERE tags->>'highway' IN ('residential','unclassified','tertiary','secondary','primary','trunk','motorway') AND country_id = 76::smallint "
CREATE VIEW
psql postgres://postgres@localhost/ingest20 -c "SELECT ingest.osm_load('/tmp/sandbox/_pkBR43_001/brazil-latest.osm.pbf.pbf','via_full','vw1_pk7600000403101_p1_via','7600000403101','befb1a28910b56920b7c10b7ae1a25d5d32f1b13931463076adebc4ab33db114.pbf',array[]::text[],5)"
ERROR:  file length too large
CONTEXT:  SQL function "jsonb_pg_stat_file" statement 1
SQL function "getmeta_to_file" statement 1
SQL function "getmeta_to_file" statement 1
PL/pgSQL function ingest.osm_load(text,text,text,bigint,text,text[],integer,text,boolean) line 12 at assignment
make: *** [makefile:147: via] Error 1

**Comment by crebollobr** [comment]
Permissão dos arquivos publicados, depois precisaria trocar com sudo manualmente para colocar no git

-rw-r--r-- 1 postgres postgres     148 fev 26 19:31 block/distrib_name_ghs.csv
-rw------- 1 postgres postgres   55975 fev 26 19:31 block/geohashes.geojson
-rw------- 1 postgres postgres   62876 fev 26 19:31 block/pols_6.geojson
-rw------- 1 postgres postgres  121478 fev 26 19:31 block/pols_6qpx.geojson
-rw------- 1 postgres postgres  386568 fev 26 19:31 block/pols_6qpxp.geojson
-rw------- 1 postgres postgres  687845 fev 26 19:31 block/pols_6qpxr.geojson
-rw------- 1 postgres postgres  206298 fev 26 19:31 block/pols_6qpyc.geojson
-rw------- 1 postgres postgres  140901 fev 26 19:31 block/pols_6qpycy.geojson
-rw------- 1 postgres postgres  339385 fev 26 19:31 block/pols_6qpyf.geojson
-rw------- 1 postgres postgres  129945 fev 26 19:31 block/pols_6qpyf7.geojson
-rw------- 1 postgres postgres  251969 fev 26 19:31 block/pols_6qpyfk.geojson
-rw------- 1 postgres postgres  209497 fev 26 19:31 block/pols_6qpyfm.geojson
-rw------- 1 postgres postgres  294985 fev 26 19:31 block/pols_6qpyfn.geojson
-rw------- 1 postgres postgres  145740 fev 26 19:31 block/pols_6qpyfp.geojson
-rw------- 1 postgres postgres  258023 fev 26 19:31 block/pols_6qpyfq.geojson
-rw------- 1 postgres postgres  904789 fev 26 19:31 block/pols_6qpz0.geojson
-rw------- 1 postgres postgres  113389 fev 26 19:31 block/pols_6qpz0k.geojson
-rw------- 1 postgres postgres  145914 fev 26 19:31 block/pols_6qpz0m.geojson
-rw------- 1 postgres postgres  386547 fev 26 19:31 block/pols_6qpz1.geojson
-rw------- 1 postgres postgres 1684884 fev 26 19:31 block/pols_6qpz2.geojson
-rw------- 1 postgres postgres  623604 fev 26 19:31 block/pols_6qpz3.geojson
-rw------- 1 postgres postgres  111891 fev 26 19:31 block/pols_6qpz3h.geojson
-rw------- 1 postgres postgres  198645 fev 26 19:31 block/pols_6qpz3j.geojson
-rw------- 1 postgres postgres  369396 fev 26 19:31 block/pols_6qpz8.geojson

**Comment by crebollobr** [comment]
/var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01
make change_parameters_parcel com várias opções não termina a execução

**Comment by crebollobr** [comment]
/var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.01
make change_parameters_via pg_db=ingest20 threshold_sum=25000000 threshold=2000000
Não termina a execução

**Comment by crebollobr** [comment]
/var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.01
make change_parameters_parcel pg_db=ingest20 threshold_sum=2500000 threshold=2000000
não termina a execução

**Comment by crebollobr** [comment]
/var/gits/_dg/preserv-BR/data/MG/BeloHorizonte/_pk0008.01
make change_parameters_geoaddress pg_db=ingest20 threshold_sum=25000000 threshold=2000000

não termina a execução

**Comment by ppKrauss** [comment]
@crebollobr , testou no _tmux_? deixa rodando por 24hs.

@0e1,  2 Mb ~ 2e6 bytes  = 2000000 . Seria interessante fornecer os parâmetros em Kb ou Mb para facilitar leitura dos zeros.

Sobre erros acima: fica a impressão que não foi testado. Importante testar e homologar o software antes de começar o uso produtivo.

**Comment by 0e1** [comment]
> /var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01 make change_parameters_parcel com várias opções não termina a execução

Quais opções? Mostre os comandos executados e a saída no terminal.
Após quanto tempo você está considerando que a execução não termina?

> make change_parameters_via pg_db=ingest20 threshold_sum=25000000 threshold=2000000

Explique os motivos de estar utilizando  `threshold_sum=25000000` e `threshold=2000000`. Eles diferem do que foi conversado em reunião. Buscamos arquivos com até 2MB (2097152 bytes). Ou seja, `threshold_sum=2097152`. 

Independente da motivação, a sequencia de comando a seguir foi executada em poucos minutos, de maneira que não consegui reproduzir o erro relatado.

```
pushd /var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01/
make me pg_db=ingest99 nointeraction=y
make all_layers pg_db=ingest99 nointeraction=y

make publicating_geojsons_parcel pg_db=ingest99 folder=/tmp/acteste
make change_parameters_parcel pg_db=ingest99 threshold_sum=25000000 threshold=2000000 folder=/tmp/acteste
```


> /var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.01
> make change_parameters_via pg_db=ingest20 threshold_sum=25000000 threshold=2000000
> Não termina a execução

Após quanto tempo você está considerando que a execução não termina?

A sequencia de comando a seguir foi executada em poucos minutos, de maneira que não consegui reproduzir o erro relatado.

```
pushd /var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.01
make me pg_db=ingest99 nointeraction=y
make all_layers pg_db=ingest99 nointeraction=y

tmux
make change_parameters_via pg_db=ingest99 threshold_sum=25000000 threshold=2000000 folder=/tmp/goteste
```

**Comment by crebollobr** [comment]
carlos@addressforall:/var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01$ make change_parameters_via pg_db=ingest20 threshold_sum=25000000 threshold=2097152
psql postgres://postgres@localhost/ingest20 -c "UPDATE ingest.donated_packcomponent SET lineage = jsonb_set(lineage, '{hcode_distribution_parameters}', '{\"p_heuristic\": 3, \"p_threshold\": 2097152, \"p_threshold_sum\": 25000000}', TRUE) WHERE id = (SELECT id FROM ingest.vw03full_layer_file WHERE isolabel_ext='BR-AC-RioBranco' AND ft_info->>'class_ftname'='via');"
UPDATE 1
make publicating_geojsons_via
make[1]: Entering directory '/var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01'
mkdir -m777 -p /var/gits/_dg/preservCutGeo-BR2021/data/AC/RioBranco/_pk0042.01/via
 Save ls /var/gits/_dg/preservCutGeo-BR2021/data/AC/RioBranco/_pk0042.01/via before changes in /tmp/pg_io/BR-AC-RioBranco_via_ls_before.txt ---
--- Gerando arquivos em /var/gits/_dg/preservCutGeo-BR2021/data/AC/RioBranco/_pk0042.01/via ---
psql postgres://postgres@localhost/ingest20 -c "SELECT ingest.publicating_geojsons('via','BR-AC-RioBranco','/var/gits/_dg/preservCutGeo-BR2021/data/AC/RioBranco/_pk0042.01/via','1');"

**Comment by 0e1** [comment]
Veja:

`threshold_sum`: tamanho máximo que se quer que um arquivo tenha.

Então `threshold_sum=2097152` ao ínves de `threshold_sum=25000000`.

No geral, se deve variar apenas o `threshold` mantendo `threshold_sum=2097152` fixado.

**Comment by 0e1** [comment]
> /var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.01
> make change_parameters_parcel pg_db=ingest20 threshold_sum=2500000 threshold_sum=2000000
> não termina a execução

Após quanto tempo você está considerando que a execução não termina? 

Notar que a quantidade de geometrias nesse caso é da ordem de 400 mil. Então é possível que leve tempo. Usar tmux para deixar rodando.

Não deixe de considerar os comentários feitos sobre o uso de `threshold_sum` e `threshold`

**Comment by crebollobr** [comment]
Vou deixar rodando 
/var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01
make change_parameters_parcel pg_db=ingest20 threshold_sum=25000000 threshold=2097152

**Comment by crebollobr** [comment]
/var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.014
make change_parameters_via pg_db=ingest20 threshold_sum=25000000 threshold=2097152

**Comment by crebollobr** [comment]
/var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01
make change_parameters_parcel pg_db=ingest20 threshold_sum=25000000 threshold=2097152

**Comment by crebollobr** [comment]
Corrigi as execuções

**Comment by crebollobr** [comment]
carlos@addressforall:/var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.01$ make change_parameters_via pg_db=ingest20 threshold_sum=2097152 threshold=2097152

**Comment by crebollobr** [comment]
Camadas parcel não terminal a execução testado por mais quarto horas

carlos   2580346  0.0  0.0   8012  2380 pts/6    S+   10:00   0:00 make change_parameters_parcel pg_db=ingest20 threshold_sum=2097152 threshold=100000
carlos   2580363  0.0  0.0   8012  2380 pts/6    S+   10:00   0:00 make publicating_geojsons_parcel
carlos   2592386  0.0  0.0   8012  2460 pts/2    S+   15:00   0:00 make change_parameters_parcel pg_db=ingest20 threshold_sum=2097152 threshold=500000
carlos   2592403  0.0  0.0   8012  2384 pts/2    S+   15:00   0:00 make publicating_geojsons_parcel
carlos   2595043  0.0  0.0   8012  2448 pts/1    S+   15:43   0:00 make change_parameters_parcel pg_db=ingest20 threshold_sum=2097152 threshold=50000

**Comment by crebollobr** [comment]
/var/gits/_dg/preserv-BR/data/MG/GovernadorValadares/_pk0039.01
make change_parameters_parcel pg_db=ingest20 threshold_sum=2500000 threshold=100000

Gerou os arquivos com no máximo 1.1M
Outras configurações não funcionou

**Comment by ppKrauss** [comment]
@0e1 ainda precisamos entender porque falhando, e então iniciar com essas amostras a primeira versão da heurística

**Comment by crebollobr** [comment]
Outra cidade com problema no parcel
/var/gits/_dg/preserv-BR/data/GO/Goiania/_pk0054.01

**Comment by crebollobr** [comment]
Mias uma
/var/gits/_dg/preserv-BR/data/PR/Cascavel/_pk0011.01

**Comment by ppKrauss** [comment]
## Fechamento da Empreitada

Pacotes de [preserv-BR](https://github.com/digital-guard/preserv-BR/tree/main/data)  **que rodaram sem problema**:

* [BR/_pk0004.01](https://github.com/digital-guard/preserv-BR/tree/main/data/_pk0004.01/make_conf.yaml)
* [BR/_pk0004.03](https://github.com/digital-guard/preserv-BR/tree/main/data/_pk0004.03/make_conf.yaml)
* [BR/AC/RioBranco/_pk0042.01](https://github.com/digital-guard/preserv-BR/tree/main/data/AC/RioBranco/_pk0042.01/make_conf.yaml)
* [BR/ES/VilaVelha/_pk0007.01](https://github.com/digital-guard/preserv-BR/tree/main/data/ES/VilaVelha/_pk0007.01/make_conf.yaml)
* [BR/GO/Goiania/_pk0054.01](https://github.com/digital-guard/preserv-BR/tree/main/data/GO/Goiania/_pk0054.01/make_conf.yaml)
* [BR/MG/BeloHorizonte/_pk0008.01](https://github.com/digital-guard/preserv-BR/tree/main/data/MG/BeloHorizonte/_pk0008.01/make_conf.yaml)
* [BR/MG/Contagem/_pk0009.01](https://github.com/digital-guard/preserv-BR/tree/main/data/MG/Contagem/_pk0009.01/make_conf.yaml)
* [BR/MG/GovernadorValadares/_pk0039.01](https://github.com/digital-guard/preserv-BR/tree/main/data/MG/GovernadorValadares/_pk0039.01/make_conf.yaml)
* [BR/MS/CampoGrande/_pk0034.01](https://github.com/digital-guard/preserv-BR/tree/main/data/MS/CampoGrande/_pk0034.01/make_conf.yaml)
* [BR/PE/Recife/_pk0010.01](https://github.com/digital-guard/preserv-BR/tree/main/data/PE/Recife/_pk0010.01/make_conf.yaml)
* [BR/PR/Araucaria/_pk0061.01](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/Araucaria/_pk0061.01/make_conf.yaml)
* [BR/PR/Cascavel/_pk0011.01](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/Cascavel/_pk0011.01/make_conf.yaml)
* [BR/PR/Curitiba/_pk0002.01](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/Curitiba/_pk0002.01/make_conf.yaml): [README.md](https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Curitiba/_pk0002.01/README.md) informa que dados não devem ser usados.
* [BR/PR/Pinhais/_pk0014.01](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/Pinhais/_pk0014.01/make_conf.yaml)
* [BR/RJ/Niteroi/_pk0016.01](https://github.com/digital-guard/preserv-BR/tree/main/data/RJ/Niteroi/_pk0016.01/make_conf.yaml)
* [BR/RJ/RioJaneiro/_pk0078.02](https://github.com/digital-guard/preserv-BR/blob/main/data/RJ/RioJaneiro/_pk0078.02/make_conf.yaml): https://github.com/digital-guard/preserv/issues/104
* [BR/RS/CaxiasSul/_pk0069.01](https://github.com/digital-guard/preserv-BR/tree/main/data/RS/CaxiasSul/_pk0069.01/make_conf.yaml)
* [BR/RS/Gravatai/_pk0017.01](https://github.com/digital-guard/preserv-BR/tree/main/data/RS/Gravatai/_pk0017.01/make_conf.yaml)
* [BR/RS/Pelotas/_pk0080.01](https://github.com/digital-guard/preserv-BR/tree/main/data/RS/Pelotas/_pk0080.01/make_conf.yaml)
* [BR/RS/PortoAlegre/_pk0018.01](https://github.com/digital-guard/preserv-BR/tree/main/data/RS/PortoAlegre/_pk0018.01/make_conf.yaml)
* [BR/RS/SantaMaria/_pk0019.01](https://github.com/digital-guard/preserv-BR/tree/main/data/RS/SantaMaria/_pk0019.01/make_conf.yaml)
* [BR/SC/Florianopolis/_pk0053.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SC/Florianopolis/_pk0053.01/make_conf.yaml)
* [BR/SC/Joinville/_pk0035.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SC/Joinville/_pk0035.01/make_conf.yaml)
* [BR/SP/Campinas/_pk0022.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Campinas/_pk0022.01/make_conf.yaml)
* [BR/SP/Piracicaba/_pk0041.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Piracicaba/_pk0041.01/make_conf.yaml)
* [BR/SP/RibeiraoPreto/_pk0052.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/RibeiraoPreto/_pk0052.01/make_conf.yaml)
* [BR/SP/Santos/_pk0029.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Santos/_pk0029.01/make_conf.yaml)
* [BR/SP/SaoBernardoCampo/_pk0030.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/SaoBernardoCampo/_pk0030.01/make_conf.yaml)
* [BR/SP/SaoPaulo/_pk0033.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/SaoPaulo/_pk0033.01/make_conf.yaml)
* [BR/SP/Sorocaba/_pk0031.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Sorocaba/_pk0031.01/make_conf.yaml) 

Pacotes  **que rodaram duas vezes** por conta da nova versão do software:
* ...

Pacotes  **que precisaram de issue de bug** para solicitar correção:
* ...
Pacotes  **combug** com issues de bug em aberto:
* ...

**Comment by crebollobr** [comment]
Referencias:
https://github.com/digital-guard/preserv-BR/issues/76
https://github.com/digital-guard/preserv-BR/issues/68
https://github.com/digital-guard/preserv-BR/issues/69
https://github.com/digital-guard/preserv-BR/issues/70
https://github.com/digital-guard/preserv-BR/issues/71
https://github.com/digital-guard/preserv-BR/issues/72
https://github.com/digital-guard/preserv-BR/issues/73
https://github.com/digital-guard/preserv-BR/issues/74
https://github.com/digital-guard/preserv-BR/issues/75
https://github.com/digital-guard/preserv-BR/issues/76
https://github.com/digital-guard/preserv-BR/issues/77
https://github.com/digital-guard/preserv-BR/issues/79
