### ISSUE TITLE
Pendencias

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#70]
Seguir a sequência de [issue 66](https://github.com/digital-guard/preserv-BR/issues/66#issuecomment-1051006235)...

* data/_pk0001.03 sem make_conf. Resolver ou apagar. Atualizar.
* data/_pk0004.*:  conferir se atualizado e carregando pontos
* ...
----

Outros:
* No OSM a mensagem "A geração de layers requer os seguintes comandos e versões: 7z v16+; psql v12+; shp2pgsql v3+" está errado, pois cita 7z e shp2pgsql (que não deveria citar) e não cita osm2pgsql.  

----

```
addressforall:/var/gits/_dg/preserv-BR/data/_pk0004.03$ make publicating_geojsons_geoaddress audit-geojsons_geoaddress change_parameters_geoaddress
mkdir -m777 -p /var/gits/_dg/preservCutGeo-BR2021/data/_pk0004.03/geoaddress
 Save ls /var/gits/_dg/preservCutGeo-BR2021/data/_pk0004.03/geoaddress before changes in /tmp/pg_io/BR_geoaddress_ls_before.txt ---
--- Gerando arquivos em /var/gits/_dg/preservCutGeo-BR2021/data/_pk0004.03/geoaddress ---
psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.publicating_geojsons('geoaddress','BR','/var/gits/_dg/preservCutGeo-BR2021/data/_pk0004.03/geoaddress','1',9,'3');"
ERROR:  case not found
HINT:  CASE statement is missing ELSE part.
CONTEXT:  PL/pgSQL function ingest.feature_asis_export(bigint) line 6 at CASE
SQL function "publicating_geojsons_p1" statement 2
SQL function "publicating_geojsons" statement 1
SQL function "publicating_geojsons" statement 1
make: *** [makefile:104: publicating_geojsons_geoaddress] Error 1
```

**Comment by 0e1** [comment]
> `addressforall:/var/gits/_dg/preserv-BR/data/_pk0004.03$ make publicating_geojsons_geoaddress audit-geojsons_geoaddress change_parameters_geoaddress`

Após as mudanças na forma de distribuição, o targuet  `change_parameters_geoaddress`  se tornou praticamente desnecessário. Ele só será útil se quisermos testar o aumento de `threshold_sum`, em caso excepcionais. Ontem foi atualizado a seção correspondente em [Geração dos arquivos publicavéis](https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo#gera%C3%A7%C3%A3o-dos-arquivos-publicav%C3%A9is)

Nos casos fora do comum ver: https://github.com/digital-guard/preserv/blob/main/docs/pt/man-diversos.md#par%C3%A2metros-de-publica%C3%A7%C3%A3o

Em outras palavras, o targuet  `change_parameters_geoaddress` **não** faz mais parte do fluxo normal de trabalho.

**Comment by crebollobr** [comment]
data/_pk0001.03 somente planilha, acredito que podemos apagar

**Comment by crebollobr** [comment]
Incorporar em #80
