### ISSUE TITLE
RioJaneiro/_pk0078.02 make me

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#76]
```

carlos@addressforall:/var/gits/_dg/preserv-BR/data/RJ/RioJaneiro/_pk0078.02$ make me pg_db=ingest21
-- Load make_conf.yaml into the database. --
Usage: make insert_make_conf
pack_id: 78.2
[Press ENTER to continue or Ctrl+C to quit]
psql postgres://postgres@localhost/ingest21 -c "SELECT ingest.lix_insert('/var/gits/_dg/preserv-BR/data/RJ/RioJaneiro/_pk0078.02/make_conf.yaml');"
 lix_insert
------------

(1 row)

-- Updating this make --
psql postgres://postgres@localhost/ingest21 -c "SELECT ingest.lix_generate_makefile('BR','78.2');"
NOTICE:  pack_id : 782
NOTICE:  country_id : 76
NOTICE:  codec_desc_global : {"srid": "31983"}
NOTICE:  layer : geoaddress, method: shp2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: <NULL>
ERROR:  TypeError: the JSON object must be str, bytes or bytearray, not NoneType
CONTEXT:  Traceback (most recent call last):
  PL/Python function "jsonb_mustache_render", line 4, in <module>
    j = json.loads(i)
  PL/Python function "jsonb_mustache_render", line 338, in loads
PL/Python function "jsonb_mustache_render"
SQL statement "SELECT replace(jsonb_mustache_render(mkme_srcTpl || mkme_srcTplLast, ingest.jsonb_mustache_prepare(f_yaml || conf_yaml)),E'\u130C9',$$\"$$)"
PL/pgSQL function ingest.lix_generate_makefile(text,text) line 20 at SQL statement
make: *** [makefile:40: me] Error 1


```

**Comment by 0e1** [comment]
Para que eu possa ajudar, os arquivos `make_conf.yaml` e `sha256sum.txt` precisam estar disponíveis no repositório.

**Comment by crebollobr** [comment]
Tem algum procedimento que eu possa fazer? Porque a cada novo dado colocado vou precisar criar issui o processo vai ficar muito demorado

**Comment by 0e1** [comment]
Acho que você está se referindo a isso: https://github.com/digital-guard/preserv/blob/main/docs/pt/man-diversos.md#atualizar-tabelas-de-optim-atualmente-em-dl03t_main. No geral, os procedimentos estão descritos na documentação do projeto [preserv](https://github.com/digital-guard/preserv/tree/main/docs/pt) e na [wiki](https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo).

Você pode subir os arquivos make_conf.yaml e sha256sum.txt para o repositório?

**Comment by 0e1** [comment]
> Você pode subir os arquivos make_conf.yaml e sha256sum.txt para o repositório?

Arquivos disponíveis. Implementação de ingestão de arquivos geojson: https://github.com/digital-guard/preserv/issues/104

**Comment by 0e1** [comment]
O commit https://github.com/digital-guard/preserv-BR/commit/4b09bf40fdd6bf3bf1bc6bf9eb5ab10d2332374b comenta o que é referente ao `file=1`. O sha256 utilizado é o mesmo utilizado em https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Curitiba/_pk0002.01/make_conf.yaml#L9. Essa coincidência não pode existir.

**Comment by crebollobr** [comment]
Corrigido o sha256. Aguardando a implementação da ingestão geojson

**Comment by 0e1** [comment]
Ingestão de _geojson_ implementada. Ver https://github.com/digital-guard/preserv/issues/104#issuecomment-1112764173.
