### ISSUE TITLE
Inclusão da proveniência dos domínios conforme diretiva Preserv

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#78]
Em https://github.com/digital-guard/preserv/issues/106 ficou estabelecida a nova convenção para o registro das evidências de domínios. Primeiro rascunho no [commit 880d170](https://github.com/digital-guard/preserv-BR/commit/880d170f24195e143a6de63005ac98a4e04650ab).

Agora temos a pasta [data/_donorEvidence](https://github.com/digital-guard/preserv-BR/tree/main/data/_donorEvidence) com todos os domínios, relativos a doadores e a pacotes doados.  Ver exemplos de [sp.gov.br](https://github.com/digital-guard/preserv-BR/tree/main/data/_donorEvidence/sp.gov.br) e [ac.gov.br](https://github.com/digital-guard/preserv-BR/tree/main/data/_donorEvidence/ac.gov.br).

**Comment by ppKrauss** [comment]
Atualmente, pela coluna `url` de  [donatedPack.csv](https://github.com/digital-guard/preserv-BR/blob/main/data/donatedPack.csv) temos:

bhmap.pbh.gov.br
caxias.rs.gov.br
censos.ibge.gov.br
dadosabertos.goiania.go.gov.br
data.rio
datasets.ok.org.br
download.geofabrik.de
drive.google.com
geo.joaopessoa.pb.gov.br
geo.jundiai.sp.gov.br
geo.piracicaba.sp.gov.br
geo.saobernardo.sp.gov.br
geoportal.seduh.df.gov.br
geoprocessamento.joinville.sc.gov.br
geosalto.geonet.net.br
geosampa.prefeitura.sp.gov.br
geoweb.vitoria.es.gov.br
ibge.gov.br
ibge.gov.br
informacao-didc.campinas.sp.gov.br
ippuc.org.br
limeira.sp.gov.br
pinhais.pr.gov.br
recife.pe.gov.br
semplan.teresina.pi.gov.br
signh.novohamburgo.rs.gov.br
sjc.sp.gov.br
transparencia.niteroi.rj.gov.br
uberlandia.mg.gov.br
vilavelha.es.gov.br
wikidata.org

**Comment by 0e1** [comment]
Foi para https://github.com/digital-guard/preserv/issues/124.
