### ISSUE TITLE
SP-Sampa pk31.1 ainda com problema no SRID, testar alternativas

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#79]
Já foram experimentados  [`srid=31984` e `srid=29193`](https://github.com/digital-guard/preserv-BR/commit/597c01180bf16af8ab4c0009195891c0212a54ba), mas nenhum funcionou.  Outras sujestões antes de se solicitar apoio dos responsáveis (GeoSampa):

* no retorno do  [WFS](http://wfs.geosampa.prefeitura.sp.gov.br/geoserver/ows?service=wfs&version=1.0.0&request=GetCapabilities) é indicado o [EPSG:31983](https://www.spatialreference.org/ref/epsg/sirgas-2000-utm-zone-23s/). Idem [WMS](http://wms.geosampa.prefeitura.sp.gov.br/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities)

* Todos os EPSGs citados nos diversos layers do GeoSampa: 29193, 31983, 4326 e 900913; e CRS:84.

**Comment by 0e1** [comment]
Nesse [comentario](https://github.com/digital-guard/preserv-BR/issues/75#issuecomment-1090707401) mostro que os dados referentes a _building_ possuem `srid=31983` e que em outros não está definido.
Isso + o que relatou agora, aponta para `codec:descr_encode: srid=31983`.

**Comment by 0e1** [comment]
Situação já resolvido, issue pode ser fechada, conforme commits acima.
