### ISSUE TITLE
Levantamento de pendencias e produção de novos pacotes

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#80]
Revisar todos os arquivos doados até o momento, disponíveis no drive-nuvem da AddressForAll, e quando pertinente criar respectivos make_conf e README. Se aprovados, publicar.

**Comment by crebollobr** [comment]
Cidades que não foram ingestadas

Aparecida de Goiânia (pop. 590.000)
Atibaia
Cabreuva ( Verificar como usar csv https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Cabreuva/_pk0040.01 )
Canoas
Curitiba ( geojson )
Fortaleza (pop. 2,7 mi)
Gravataí (pop. 284.000) ( Falta ingestão de planilha de endereço)
João Pessoa
Jundiaí-CIJUN
Natal
São José dos Pinhais

**Comment by luisfelipebr** [comment]
README pendentes

- [ ] Aparecida de Goiânia (GO)
- [ ] Atibaia (SP)
- [ ] Bagé (RS)
- [ ] Cabreúva (SP) - verificar como usar csv https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Cabreuva/_pk0040.01
- [ ] Cachoeiro de Itapemirim (ES) - aguardar, possui 1 pendência
- [ ] Campinas (SP) - checar
- [ ] Canoas (RS)
- [ ] Curitiba (PR)
- [ ] Fortaleza (CE)
- [ ] Gravataí (RS) - falta ingestão de planilha de endereço
- [ ] Guarulhos (SP)
- [ ] João Pessoa (PB)
- [ ] Jundiaí (SP)
- [ ] Manaus (AM)
- [ ] Maringá (PR)
- [ ] Natal (RN)
- [ ] Novo Hamburgo (RS)
- [ ] Rio de Janeiro (RJ)
- [ ] Salvador (BA)
- [ ] Santa Cruz do Sul (RS)
- [ ] Toledo (PR)

**Comment by crebollobr** [comment]
Falta README. md de São Paulo e Caxias do SuL

**Comment by crebollobr** [comment]
Makefile para 
DuqueCaxias
SaoJoseCampos
Guarulhos
Cabreuva
SaoVicente
Jundiai
Osasco
Itu
_pk0001.03 IBGE
PatoBranco
Bage

**Comment by crebollobr** [comment]
Verificar se faremos ingestão de Neoenergia

**Comment by crebollobr** [comment]
Verificar a ingestão de Palmas TO

**Comment by crebollobr** [comment]
TODO: Verificar se todas as pastas do git é publicada, resolver ou apagar 
#70

**Comment by ppKrauss** [comment]
> TODO: Verificar se todas as pastas do git é publicada, resolver ou apagar

Primeiro classificar os que possuem arquivo (SHA1 ainda existe) e os que não possuem. Exemplos:
*  Guarujá existia, mas aparentemente o hash indicado não está na preservação, http://dl.digital-guard.org/download/39ca8edb1a827
* DuqueCaxias parece ter seus arquivos, testar downloads
* .... avaliar um a um

PS: caso de Curitiba é um problema de licença a ser comprovada, aí se ok precisamos dos dados do Santamariense para usar.

**Comment by 0e1** [comment]
Incluir na lista de pendencias: https://github.com/digital-guard/preserv-BR/issues/106.

**Comment by luisfelipebr** [comment]
@crebollobr adicionei o README de Maringa. Como não encontrei o arquivo zip no servidor, me refiro ao arquivo excel

**Comment by crebollobr** [comment]
> @crebollobr adicionei o README de Maringa. Como não encontrei o arquivo zip no servidor, me refiro ao arquivo excel

Seria o caso de criar um zip com o arquivo excel 

arquivo.xls compactar para arquivo.zip, fazer o sha256 e copiar para o servidor

**Comment by luisfelipebr** [comment]
@crebollobr adicionei o README de Fortaleza. Esse doador possui licença explícita. Como ficou o workflow das licenças?

**Comment by luisfelipebr** [comment]
A licença de Fortaleza está em formato eml. Subi para o servidor e o sha256sum está disponível [aqui](https://github.com/digital-guard/preserv-BR/tree/main/data/CE/Fortaleza/_pk0097.01). @ppKrauss não é interessante adicionar o link/sha na planilha donatedPack quando a licença é explícita (conforme sugeriu o Thierry)? E adicionar as evidências na página de download (teste2)?

**Comment by luisfelipebr** [comment]
@crebollobr os README abaixo estão prontos, com yaml pendente. Favor verificar se existe alguma pendência.

- [ ] Fortaleza - CE
- [ ] Vitoria - ES
- [ ] Manaus - AM
- [ ] Brasilia- DF
- [ ] JoaoPessoa - PB
- [ ] Teresina - PI
- [ ] ParanaCidade - PR
- [ ] Toledo - PR
- [ ] JiParana - RO
- [ ] Natal - RN
- [ ] Bage - RS

**Comment by luisfelipebr** [comment]
@crebollobr no caso dos municípios que eu fiz apenas o README, você prefere que eu escreva o yaml ou você escreve?

Municípios:

> * [ ]  Fortaleza - CE
> * [ ]  Vitoria - ES
> * [ ]  Manaus - AM
> * [ ]  Brasilia- DF
> * [ ]  JoaoPessoa - PB
> * [ ]  Teresina - PI
> * [ ]  ParanaCidade - PR
> * [ ]  Toledo - PR
> * [ ]  JiParana - RO
> * [ ]  Natal - RN
> * [ ]  Bage - RS
> * [ ]  Niteroi - RJ

**Comment by luisfelipebr** [comment]
@crebollobr vamos migrar essa issue para https://docs.google.com/spreadsheets/d/1PQGiqN7WayLDx8c0jD4qFPUdPL6sP8U1d3CvddbKU7U/edit?usp=sharing

**Comment by crebollobr** [comment]
Vou fechar essa issue, pendencias dela em outras issues
