### ISSUE TITLE
SP-Cabreuva-pk0040, retomar JOIN ou decisões em 

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#81]
Atuallmente temos apenas READMEem  [SP/Cabreuva/_pk0040.01](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Cabreuva/_pk0040.01). 

Em setembro de 2020  Cabreúva foi indicada como parte do projeto [VIVO - Cidades para teste ](https://github.com/AddressForAll/LIXO-digital-preservation-BR/projects/1)... Seria oportuno retomar, abaixo copia/cola das observações do @IgorEliezer em 2020:

---

### Dados
- [x] Feito?
* População estimada [2020]: 50.429 pessoas
* População no último censo [2010]: 41.604 pessoas
* Densidade demográfica [2010]: 159,87 hab/km²

Fonte: https://cidades.ibge.gov.br/brasil/sp/cabreuva/panorama

### O que temos
- [x] Feito?
Salvo na Preservação:
 - cad:Mapa básico
 - csv:Planilha ID-Endereço
 - pdf:Mapas do Plano Diretor (2 arquivos)

### Volumetria OSM
- [ ] Feito?
(em andamento)

### Volumetria A4A
- [ ] Feito?
(em andamento)

### O que mais precisa ser feito
- [x] Corrigir nomes das vias (acréscimo de 120 km)
- [ ] Gerar eixos de vias com nomes atualizados (na fila)
- [ ] PostGIS: Distribuir pontos de endereço ao longo dos eixos

**Comment by crebollobr** [comment]
@ppKrauss acredito que seja pouco proveitoso os dados, depende de osm
e o dado de geoadress relação_.csv as vias estão sem acento e a numeração predial tem muitos S/N

quantidade x numeração predial
502 000SN
929 S/N
6241 00S/N

total = 13728

**Comment by crebollobr** [comment]
Trabalhando junto com a #80

**Comment by crebollobr** [comment]
@luisfelipebr Poderia verificar com a prefeitura sobre a qualidade dos dados? Se eles tem dados novos?

**Comment by ppKrauss** [comment]
Ok, pontos são *geoaddress* e são bem-vindos (!), mesmo sem endereço escrito.

Quanto aos casos de numeração predial ruim, cabe justamente ao make_conf filtrar os lixos: <br/>` CASE WHEN house_number IN ( '000SN','S/N','00S/N')  THEN NULL ELSE house_number END`

**Comment by crebollobr** [comment]
feito.

**Comment by ppKrauss** [comment]
@0e1 agendar com @crebollobr um dia para fazerem juntos a transcrição do velho ["readme humano"](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Cabreuva/_pk0040.01#readme) para YAML, garantindo que cometários relevantes fiquem no Readme automático.

@0e1  também precisa avaliar como será a publicação de CSV isolado, sem GeoJSON.

**Comment by crebollobr** [comment]
Podemos fazer uma issue empreitada para README automático
