### ISSUE TITLE
Atualizar planilha Donor com doadores em homologação

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#83]
Os potenciais doadores prospectados no CRM, quando estão  "final do funil"  é porque já enviaram dados, e aguardam apenas que seus dados sejam homologados para efetivar a doação. Percebemos que nesta etapa são raros os casos de não-homologação. Em função disso decidiu-se que a planilha Donor pode receber dados com coluna *is_homologated*  em *false* (não-homologado).

Sincronizar a planilha donor com a planilha do CRM introduzindo no CRM a coluna de donor_id (nula para os que não forneceram ainda arquivos) e gerenciar datas. A planilha de CRM também deve ser gerenciada pelo banco de dados, e um extrato seu publicado em git.

**Comment by luisfelipebr** [comment]
Planilha [donor.csv](https://github.com/digital-guard/preserv-BR/blob/main/data/donor.csv) atualizada com doadores em prospecção.

@0e1 inseri duas novas colunas no final. Se aparecer um bug novo, pode ser por conta disso.

**donor_date**: data de cadastro do doador (primeiro contato)

donor_status:
0 = Tentativas de contato realizadas
1 = Contatos com doadores potenciais que respondem ao nosso chamado;
2 = Doadores efetivos: entregam alguma coisa mesmo que inutil
3 = Doadores com pacotes aprovados e publicados (packs)
