### ISSUE TITLE
Relatório estatístico das ingestões

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#84]
(em construção)

**Comment by luisfelipebr** [comment]
O relatório estatístico é feito de várias seções, a primeira é o resumo executivo.

## Resumo executivo

1. Introdução - explicar o objetivo do instituto - pontos de endereço

2. Explicar cada etapa (metodologia) e os tipos de dados (bruto, filtrados e consolidados)

3. Estatística prospecção (contatos) - funil
- Percentual de sucesso - quantos forneceram arquivos?
- Quanto tempo demoraram para fornecer arquivos?

5. Estatística dados brutos:
- Quantos arquivos de cada tipo? Total, por país, estado e município.

6. Estatística dados filtrados completos:
- Quantos pontos de endereço? Total, por país, estado e município.
- Quantos pontos de endereço ao longo do tempo?

7. Estatística dados filtrados incompletos:
- Volumetria potencial por interpolação
- Volumetria potencial de criação de endereços a partir de parcels

## Detalhes...

**Comment by luisfelipebr** [comment]
@ppKrauss preciso marcar outra conversa para alinhar o que incluir no relatório. Mas por enquanto, todos os dados que preciso estão na tabela gerada pelo Claiton. [Rascunho](https://luisfelipebr.github.io/temp/)

**Comment by luisfelipebr** [comment]
Migrou para https://github.com/digital-guard/stats/issues
