### ISSUE TITLE
RioJaneiro/_pk0078.02 Alteração em nome de arquivo make_conf.yaml

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#87]
Alteração ca3372bbecd51a34481c39af3c194db84c3fd6b578a14f58aa8f787d3f86caf4.zip para 
ca3372bbecd51a34481c39af3c194db84c3fd6b578a14f58aa8f787d3f86caf4.rar

Qual o target para atualizar isso no banco de daodos?

------------
 
(1 row)

-- Updating this make --
psql postgres://postgres@localhost/ingest20 -c "SELECT ingest.lix_generate_makefile('BR','78.2');"
NOTICE:  pack_id : 782
NOTICE:  country_id : 76
NOTICE:  codec_desc_global : {"srid": "31983"}
NOTICE:  layer : via, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : block, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : nsvia, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : parcel, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : geoaddress, method: shp2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: <NULL>
ERROR:  TypeError: the JSON object must be str, bytes or bytearray, not NoneType
CONTEXT:  Traceback (most recent call last):
  PL/Python function "jsonb_mustache_render", line 4, in <module>
    j = json.loads(i)
  PL/Python function "jsonb_mustache_render", line 338, in loads
PL/Python function "jsonb_mustache_render"
SQL statement "SELECT replace(jsonb_mustache_render(mkme_srcTpl || mkme_srcTplLast, ingest.jsonb_mustache_prepare(f_yaml || conf_yaml)),E'\u130C9',$$\"$$)"
PL/pgSQL function ingest.lix_generate_makefile(text,text) line 20 at SQL statement
make: *** [makefile:540: me] Error 1

```

carlos@addressforall:/var/gits/_dg/preserv-BR/data/RJ/RioJaneiro/_pk0078.02$ make me pg_db=ingest20
-- Load make_conf.yaml into the database. --
Usage: make insert_make_conf
pack_id: 78.2
[Press ENTER to continue or Ctrl+C to quit]
psql postgres://postgres@localhost/ingest20 -c "SELECT ingest.lix_insert('/var/gits/_dg/preserv-BR/data/RJ/RioJaneiro/_pk0078.02/make_conf.yaml');"
 lix_insert 
------------
 
(1 row)

-- Updating this make --
psql postgres://postgres@localhost/ingest20 -c "SELECT ingest.lix_generate_makefile('BR','78.2');"
NOTICE:  pack_id : 782
NOTICE:  country_id : 76
NOTICE:  codec_desc_global : {"srid": "31983"}
NOTICE:  layer : via, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : block, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : nsvia, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : parcel, method: geojson2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: "geojson"
NOTICE:  layer : geoaddress, method: shp2sql
NOTICE:  codec resultante : {"srid": "31983"}
NOTICE:  codec_extension from method: <NULL>
ERROR:  TypeError: the JSON object must be str, bytes or bytearray, not NoneType
CONTEXT:  Traceback (most recent call last):
  PL/Python function "jsonb_mustache_render", line 4, in <module>
    j = json.loads(i)
  PL/Python function "jsonb_mustache_render", line 338, in loads
PL/Python function "jsonb_mustache_render"
SQL statement "SELECT replace(jsonb_mustache_render(mkme_srcTpl || mkme_srcTplLast, ingest.jsonb_mustache_prepare(f_yaml || conf_yaml)),E'\u130C9',$$\"$$)"
PL/pgSQL function ingest.lix_generate_makefile(text,text) line 20 at SQL statement
make: *** [makefile:540: me] Error 1


```

**Comment by crebollobr** [comment]
Essa issue faz referencia a #80

**Comment by 0e1** [comment]
Targuet aqui: https://github.com/digital-guard/preserv/blob/main/docs/pt/man-diversos.md#atualizar-tabelas-de-optim-atualmente-em-dl03t_main

Mas não vai funcionar se a tabela donatepack.csv estiver preenchida errada. Linhas referentes ao Rio de Janeiro estão confusas, então os dados referentes a BR não são carregados.

**Comment by crebollobr** [comment]
O erro:
```
ERROR:  duplicate key value violates unique constraint "donated_packfilevers_pack_id_pack_item_pack_item_accepted_d_key"
DETAIL:  Key (pack_id, pack_item, pack_item_accepted_date)=(7600007802, 1, 2022-01-28) already exists.
CONTEXT:  SQL statement "

```

Aparentemente não vejo linhas duplicadas no csv.
(7600007802, 1, 2022-01-28).

```
07802	78	2	001	RJ-RJO	luis	2022-01-28	BR-RJ-RioJaneiro	Endereços
```

Esse id 7600007802 como é gerado? 76 pode ser valor de outra linha?

**Comment by 0e1** [comment]
Na doc https://github.com/digital-guard/preserv/blob/main/docs/pt/man-diversos.md#atualizar-tabelas-de-optim-atualmente-em-dl03t_main tem detalhes.

A questão é:

Você quer inserir um novo _sha256_ em `optim.donated_PackFileVers` com `(pack_id, pack_item, pack_item_accepted_date)` igual a de um _sha256_ já existente na tabela. `UNIQUE(pack_id,pack_item,pack_item_accepted_date)` vai impedir a inserção.

Então, se você quer manter `(pack_id,pack_item,pack_item_accepted_date)` e alterar o _sha256_ é preciso alterar diretamente no banco de dados. Não tem targuet para isso, conforme dito na doc+issue referenciada por ela.

Eu executei:

`UPDATE optim.donated_packfilevers SET hashedfname = 'ca3372bbecd51a34481c39af3c194db84c3fd6b578a14f58aa8f787d3f86caf4.rar' WHERE id = 7600007802101;
`
para atualizar o `sha256`.

E depois executei

```
pushd /var/gits/_dg/preserv/src
make load_optim_csv pg_datalake=dl03t_main
```
para atualizar a DL03t_main.

Então, situação normalizada.

As issues https://github.com/digital-guard/preserv-BR/issues/87, https://github.com/digital-guard/preserv-BR/issues/91, https://github.com/digital-guard/preserv-BR/issues/89 podem ser fechadas.
