### ISSUE TITLE
Homologação SaoPaulo (_pk35)

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv-BR#9]
Durante o processo de homologação de _pk35 foi reportado o erro:

```
psql postgres://postgres@localhost/ingest2 -c "SELECT ingest.any_load('shp2sql','/tmp/sandbox/_pk35_001/SHP_edificacao','building_none','pk35_001_p1_building','35_001','8e7be760f94bb385bb1b6a47feee3afce9c0fcf48317b554834a5ac30bc5a0cf.zip',array)"
ERROR:  syntax error at or near ")"
LINE 1: ...bb1b6a47feee3afce9c0fcf48317b554834a5ac30bc5a0cf.zip',array)
```
Para esse conjunto de dados o impedimento para a ingestão era a falta de tratamento de múltiplos arquivo em um layer.

O templates [make_ref035a.mustache.mk](https://github.com/digital-guard/preserv-BR/blob/main/src/maketemplates/make_ref035a.mustache.mk) e [common003_shp2pgsql_multiplefiles_zipped.mustache](https://github.com/digital-guard/preserv-BR/blob/main/src/maketemplates/common003_shp2pgsql_multiplefiles_zipped.mustache) fazem esse tratamento.

Meu entendimento é que o erro reportado está na incompletude do yaml atual. Precisamente, acho que faltam `query_view` ou `sql_select`. Essas variáveis são opcionais, mas pelo menos uma delas deve existir conforme  [common001_pgAny_load.mustache](https://github.com/digital-guard/preserv-BR/blob/main/src/maketemplates/common001_pgAny_load.mustache), caso contrário dá problema no último parâmetro da  `ingest.any_load`

Ajustar [make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoPaulo/_pk035/make_conf.yaml) deve resolver o erro reportado.

**Comment by 0e1** [comment]
Como esperado, utilizar `query_view` ou `sql_select` resolve o problema apontado.

No entanto, superado esse problema, existe outro.

A função [jsonb_pg_stat_file](https://github.com/AddressForAll/WS/blob/master/src/pubLib.sql#L156), utilizada em [getmeta_to_file](https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L528), que por sua vez é utilizada em [any_load](https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L634), espera um caminho absoluto de um arquivo dado por `orig_filename` em [make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoPaulo/_pk035/make_conf.yaml).

No entanto, não existe um arquivo, são vários arquivos.

Exemplo do erro:

```
...

Postgis type: MULTIPOLYGON[2]
Field ed_id is an FTDouble with width 20 and precision 0
Field ed_area is an FTDouble with width 15 and precision 5
Field ed_altura is an FTDouble with width 15 and precision 5
Shapefile type: Polygon
Postgis type: MULTIPOLYGON[2]
psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.any_load('shp2sql','/tmp/sandbox/_pk35_001/SHP_edificacao','building_none','pk35_001_p1_building','35_001','8e7be760f94bb385bb1b6a47feee3afce9c0fcf48317b554834a5ac30bc5a0cf.zip',array['gid'])"
ERROR:  could not stat file "/tmp/sandbox/_pk35_001/SHP_edificacao.shp": No such file or directory
CONTEXT:  SQL function "jsonb_pg_stat_file" statement 1
SQL function "getmeta_to_file" statement 1
SQL function "getmeta_to_file" statement 1
PL/pgSQL function ingest.any_load(text,text,text,text,real,text,text[],text,boolean) line 16 at assignment
make: *** [makefile:77: building] Error 1
```

**Comment by ppKrauss** [comment]
Esses erros não deveriam abortar o processo:

* *NOTICE:  Self-intersection at or near point ...*
* *Field ed_id is an FTDouble with width 20 and precision ...*

Se for o caso ignorar registros com erro e ficar sõ com os isentos de falha.

**Comment by ppKrauss** [comment]
Erro grave, precisa ser resolvido, 

*ERROR:  could not stat file "/tmp/sandbox/_pk35_001/SHP_edificacao.shp": No such file or directory*

**Comment by ppKrauss** [comment]
Sobre o loop e o *"SSL SYSCALL error"*, pode ser a memória e CPU do servidor (e máquinas virtuais em geral) que são limitados. 

1. Se demonstrar que roda com alguns shapes, software entregue, avisar Carlos que tem problema de configuração para ele resolver no psql
2. Pode ser problema de COMMIT demorado, fecha o commit do INSERT de dados a cada bloco para não sobrecarregar.

**Comment by 0e1** [comment]
Os commits resolvem essa situação:
https://github.com/digital-guard/preserv-BR/commit/1f22166f05064bb45e3333e513c2daaf569baf73
https://github.com/AddressForAll/WS/commit/75af36ea8fba5e3d8156539a5c5a4eb0c5064758
