### ISSUE TITLE
README.md Bage/_pk0082.01

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#90]
```

VIA (logradouros)
Abrir LOGRADOUROS.geojson
Copiar para o diretório alvo
id = gid (id)
logradouro = name

Quando indicar o arquivo, abaixo colocar no lado esquerdo o nome dos campos do arquivo e no lado direito os campos do banco de dados

importar  PARCEL rural tambem, fazendo join com o Urbano 

Não aparece a imagem 

Colocar todos os arquivos que recebemos e não usamos como comentário 


```

**Comment by crebollobr** [comment]
Essa issue faz referencia a #80

**Comment by luisfelipebr** [comment]
@crebollobr atualizei o README de Bagé. É necessário arrumar no make_conf: o SRID do arquivo LOTES_RURAIS e importar o `house_number` do arquivo LOTES_URBANOS

**Comment by crebollobr** [comment]
@0e1 Poderia confirmar se é possível fazer join LOTES_RURAIS  e LOTES_URBANOS com srid diferentes?

**Comment by crebollobr** [comment]
é possível converter o srid do LOTES_RURAIS e fazer ingestão dele junto com o LOTES_URBANOS

**Comment by crebollobr** [comment]
Ou usar ST_Transform no make_conf 

sql_select: [['id AS gid','logradouro AS via_name','geometry AS geom'],['id AS gid','geometry AS ST_Transform(geom,31981)']]

**Comment by ppKrauss** [comment]
> @ppKrauss, neste caso faz somente a ingestão do arquivo LOTES_URBANOS e não LOTES_RURAIS? Ou seria o caso de alteração no código?

1. se nada for automatizável, sim ficar só com os URBANOS.
2. se for automatizável, sem gambiarra humana, tudo usando make_conf, resolvido. A solução usando ST_Transform é boa pois tá dentro do make_conf, pode usar (!).

**Comment by 0e1** [comment]
Tenham em mente o seguinte:

- ingestão de múltiplos arquivos está disponível para o método `shp2sql`;
- ingestão de múltiplos arquivos utilizando um _array_ não está disponível se usar `sql_view`, apenas `sql_select`;

O caso em questão envolve arquivos _geojson_. Conforme https://github.com/digital-guard/preserv/issues/104#issuecomment-1112764173 `sql_select` não é suportado pelo método `geojson2sql`, apenas `sql_view`.

Então, o suporte para esse caso tem que ser desenvolvido ou utilizar o item 1, ficando só com os urbanos·

**Comment by crebollobr** [comment]
@ppKrauss em qual solução podemos trabalhar?

**Comment by 0e1** [comment]
Dá reunião: fazer pacotes diferentes, com o mesmo fornecedor.

**Comment by crebollobr** [comment]
Não precisou criar novo pacote, usado ST_Transform(geometry,31981) na ingestão
