### ISSUE TITLE
README.md Guarulhos

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#92]
```
Está usando WinRAR licenciado? seria melhor optar por um compactador software livre  

Bairros (nsvia)
Abrir pg_cartografia_bairros.zip
Selecionar todos os arquivos
Copiar para o diretório alvo
Campos relevantes:
id_bairro = id do bairro
bairro = nome do bairro

Quando indicar o arquivo, abaixo colocar no lado esquerdo o nome dos campos do arquivo e no lado direito os campos do banco de dados

Colocar como comentário os arquivos não usados e os campos não usados


```

**Comment by crebollobr** [comment]
Essa issue faz referencia a #80

**Comment by luisfelipebr** [comment]
@crebollobr revisar geoaddress

**Comment by crebollobr** [comment]
Revisado

**Comment by crebollobr** [comment]
@0e1 Confirmar se é possível fazer join entre camadas geoaddress e via?

**Comment by 0e1** [comment]
Não é.

Aqui estão descritas as possibilidades de join entre layers: https://github.com/digital-guard/preserv/blob/main/docs/pt/ftypes.md

Então, uma possibilidade é fazer a ingestão do que for necessário como address, para fazer o join entre geoaddress e address.

Deixando claro que não estou dizendo para ingerir via como address. Estou dizendo para ingerir via como via, e depois ingerir o que precisar para complementar geoaddress como address.

**Comment by crebollobr** [comment]
@0e1 seria um procedimento manual: gerar um arquivo para layer address?
Ou seria algo tratado no make_conf.yaml?

**Comment by 0e1** [comment]
Teoricamente, `address` seria igual a `via`, exceto por nome do _layer_ e `sql_view` (ou `sql_select`) diferentes. Por exemplo, `sql_view` não precisaria incluir _geom_.

Estou aventando a possibilidade, tem que testar e verificar o resultado diretamente nas respectivas tabelas, principalmente depois de ser realizado o make join, uma vez que address feito dessa forma, provavelmente, terá muita repetição.

Se julgar não conveniente testar, a outra opção é fazer manualmente um arquivo com aquilo que quer.

**Comment by crebollobr** [comment]
Acabei fazendo na mão o join

```
make all_layers 
From file_id=1 inserted type=via_full. 
From file_id=2 inserted type=nsvia_full.
From file_id=3 inserted type=geoaddress_full.

create table tmp_via as 
select 
	properties->'cod_log' AS cod_log, properties->'via_name' as via_name from ingest.feature_asis 
where 
	ingest.feature_asis.file_id = 1 AND (properties->'via_name')::text <> '' and (properties->'via_name')::text <> 'null'
group by 
	properties->'cod_log',properties->'via_name'
;

SELECT 6916
Tem via com via_name nulo vindo dos arquivos

UPDATE ingest.feature_asis as t1 
SET properties = jsonb_set(t1.properties, '{via_name}', COALESCE(t2.via_name, '""') , TRUE )
FROM tmp_via as t2
where t1.file_id=3 and T1.properties->'cod_log' = t2.cod_log;

UPDATE 284101

select count(properties) from ingest.feature_asis
where file_id = 3;
 289917


Foram inseridos 284101 registros de via_name no geoadress do total de 289917 tuplas

Vou colocar isso no README.MD

```

**Comment by crebollobr** [comment]
Feito
