### ISSUE TITLE
Criar uma função no makefile para alterar arquivo/hash 

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#96]
Criar uma função no makefile para alterar arquivo/hash
Referencia #87

Na doc https://github.com/digital-guard/preserv/blob/main/docs/pt/man-diversos.md#atualizar-tabelas-de-optim-atualmente-em-dl03t_main tem detalhes.

A questão é:

Você quer inserir um novo _sha256_ em `optim.donated_PackFileVers` com `(pack_id, pack_item, pack_item_accepted_date)` igual a de um _sha256_ já existente na tabela. `UNIQUE(pack_id,pack_item,pack_item_accepted_date)` vai impedir a inserção.

Então, se você quer manter `(pack_id,pack_item,pack_item_accepted_date)` e alterar o _sha256_ é preciso alterar diretamente no banco de dados. Não tem targuet para isso, conforme dito na doc+issue referenciada por ela.

Eu executei:

`UPDATE optim.donated_packfilevers SET hashedfname = 'ca3372bbecd51a34481c39af3c194db84c3fd6b578a14f58aa8f787d3f86caf4.rar' WHERE id = 7600007802101;
`
para atualizar o `sha256`.

E depois executei

```
pushd /var/gits/_dg/preserv/src
make load_optim_csv pg_datalake=dl03t_main
```
para atualizar a DL03t_main.

Então, situação normalizada.

As issues https://github.com/digital-guard/preserv-BR/issues/87, https://github.com/digital-guard/preserv-BR/issues/91, https://github.com/digital-guard/preserv-BR/issues/89 podem ser fechadas.

_Originally posted by @0e1 in https://github.com/digital-guard/preserv-BR/issues/87#issuecomment-1115136433_

**Comment by 0e1** [comment]
Target criado em https://github.com/digital-guard/preserv/commit/337f7d6b8cf0d293615c4f28e5ae97b92f006e9f

Uso:
```
pushd /var/gits/_dg/preserv/src
make sha256_update pg_datalake=<datalake com schema optim> id=<id de optim.donated_packfilevers> oldsha256=<sha256 atual que será substituído> newsha256=<sha256 que substituirá oldsha256>
```

**Exemplo** de saída completa da execução do target:
```
anon@addressforall:/var/gits/_dg/preserv/src$ make sha256_update pg_datalake=dl03t_main id=85800000101101 oldsha256=13456d87d099ac5b0a16203b1b41081e2a520208656f5bd963bf76d6cd738679.pbf newsha256=13456d87d099ac5b0a16203b1b41081e2a520208656f5bd963bf76d6cd738678.pbf
Update sha256 in optim.donated_packfilevers
Old sha256: 13456d87d099ac5b0a16203b1b41081e2a520208656f5bd963bf76d6cd738679.pbf
New sha256: 13456d87d099ac5b0a16203b1b41081e2a520208656f5bd963bf76d6cd738678.pbf
id: 85800000101101
pg_datalake: dl03t_main
Usage: make sha256_update pg_datalake=<datalake with optim schema> id=<id from optim.donated_packfilevers> oldsha256=<sha256 that will be changed> newsha256=<sha256 that will replace oldsha256>
[Press ENTER to continue or Ctrl+C to quit]
psql postgres://postgres@localhost/dl03t_main -c "UPDATE optim.donated_packfilevers SET hashedfname = '13456d87d099ac5b0a16203b1b41081e2a520208656f5bd963bf76d6cd738678.pbf' WHERE id = 85800000101101 AND hashedfname = '13456d87d099ac5b0a16203b1b41081e2a520208656f5bd963bf76d6cd738679.pbf';"
UPDATE 1
```

É muito importante ter em mente que esse target é apenas para situações do tipo:
- informei errado o sha256 na momento de criar o make_conf, preciso trocar e não quero executar um _update_ diretamente na base de dados.

Para qualquer  outra situação é preciso avaliar se não é o caso de uma nova versão.
