### ISSUE TITLE
SaoVicente/_pk0032.01 dado estranho house_number

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#97]
SaoVicente/_pk0032.01 dado estranho house_number
![erro01](https://user-images.githubusercontent.com/22559999/167232119-8696b4bf-2ffd-42d4-807b-312f2b507288.PNG)

**Comment by crebollobr** [comment]
Issue componente #80

**Comment by 0e1** [comment]
Por favor, ao reportar um erro, ser mais explicito ao que está se referindo.

Supondo que você se refere ao que aparece na _popup_, isso não é estranho. `error_code = 100` significa se tratar de um representante, escolhido entre dados duplicados. Isso por ser visto em https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L1605.
