### ISSUE TITLE
Publicação preservCutGeo-BR2021/tree/20220506/data/SP/SaoVicente

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#98]
Avaliar o dado na branch

https://github.com/digital-guard/preservCutGeo-BR2021/tree/20220506/data/SP/SaoVicente

**Comment by 0e1** [comment]
Por enquanto, eu acho que esses dados não podem ser homologados.

Visualmente parece que está tudo correto com os arquivos na branch. No entanto:

1. [Readme](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoVicente/_pk0032.01/README.md) contráditório. É dito que _a prefeitura não forneceu material geoprocessável, somente um desenho CAD ..._. Mas se foi possível extrair os dados que estão na branch, então _não_ foi fornecido apenas um desenho. Então, acho que pode ser dito o formato fornecido e comentado o procedimento para gerar o csv a partir do cad;
2. [make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoVicente/_pk0032.01/make_conf.yaml) não existe em https://github.com/digital-guard/preserv-BR/tree/main/data/SP/SaoVicente/_pk0032.01;
3. Existência da pasta _tratamento_. Essa não é uma pasta prevista na estrutura do diretório. Meu entendimento é de que o seu conteúdo pode ser juntado com o readme.md que está um nível acima e a pasta excluída.

**Comment by crebollobr** [comment]
Existem dois readme.md, um com o dado original e outro com o tratamento.
Pode ser uma solução juntar os readmes ou manter em pacotes diferentes, pk com donor diferente. O dado foi originado pela empresa Addressforall
